### ISSUE TITLE
Unable to use EKS IAM role 

### ISSUE THREAD

**Issue by jdziat** [kubernetes-sigs/aws-ebs-csi-driver#1024]
/kind bug

**What happened?**
When using IAM role and policy with a helm chart I get the below error:
```
1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"ebs-test", UID:"090eba72-a253-424c-9753-f4a65ed2f820", APIVersion:"v1", ResourceVersion:"115104014", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ebs-sc-fast": rpc error: code = Internal desc = Could not create volume "pvc-090eba72-a253-424c-9753-f4a65ed2f820": could not create volume in EC2: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message:
```
Same Policy works when using a kubernetes secret with the aws key and secret.

**What you expected to happen?**
The role should be used successfully when attempting to perform the operation.

**How to reproduce it (as minimally and precisely as possible)?**
Attempt to create and use the IAM role auth policy using the helm chart and terraform module: `terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc`

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.20.7-eks-d88609
- Driver version: helm chart: 2.1.0

**Comment by nirmalaagash** [comment]
@jdziat Can you please share the input values that you used when creating using [terraform](https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/docs/example-iam-policy.json) and can you confirm the [policy](https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/docs/example-iam-policy.json) that you used?

**Comment by vtomasr5** [comment]
Hi,

I see the same problem.
I'm using:
* EKS 1.21
* Helm chart aws-ebs-csi-driver v2.1.0

Role policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateSnapshot",
                "ec2:AttachVolume",
                "ec2:DetachVolume",
                "ec2:ModifyVolume",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeInstances",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DescribeVolumesModifications",
                "ec2:CreateVolume",
                "ec2:DeleteVolume",
                "ec2:DeleteSnapshot",
                "ec2:CreateTags",
                "ec2:DeleteTags"
            ],
            "Resource": "*"
        }
    ]
}
```

I also tried the example https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json with the same result.

**Comment by vtomasr5** [comment]
BTW, using the helm chart 1.2.x it works fine with either IAM policy.

**Comment by jdziat** [comment]
Thanks @vtomasr5 

@nirmalaagash i can make a gist of the terraform module i've created it's not the most condensed thing. Also the secret name should be customizable since all the aws-csi charts use that same name it leads to conflict and possible collisions.

**Comment by nirmalaagash** [comment]
@jdziat I tried creating the iam role using the terraform registry [module](https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-assumable-role-with-oidc). I did not face any issue in creating a volume.
Please ensure you provide these required inputs for the terraform,

- provider_url `<OIDC Provider URL from the Cluster>`
- role_policy_arns `<ARN of the policy that you want to attach>`
- oidc_fully_qualified_subjects `<["system:serviceaccount:kube-system:ebs-csi-controller-sa"]>`
- oidc_fully_qualified_audiences `<["sts.amazonaws.com"]>`
- create_role `<true>`
- role_name `<ROLE_NAME>`
- number_of_role_policy_arns `<NUMBER OF ROLE POLICY ARNS>`

Once after you create the role using terraform, ensure that you annotate the service account 'ebs-csi-controller-sa' with the ARN of the role that you just created.

> kubectl annotate serviceaccount ebs-csi-controller-sa -n kube-system eks.amazonaws.com/role-arn=arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>

Restart the pods using 

> kubectl delete pods  -n kube-system -l=app=ebs-csi-controller

Let me know if you face any issues. In case you face any issues, please share the input values that you are passing through terraform.

**Comment by Kaelten** [comment]
I was having a similar sounding issue, I was able to use this values file with the helm chart to get things working. 

```yaml
image:
  repository: 602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/aws-ebs-csi-driver
enableVolumeResizing: 'true'
enableVolumeSnapshot: 'true'
controller:
  serviceAccount:
    create: 'true'
    name: ebs-csi-controller-sa
    annotations:
      eks.amazonaws.com/role-arn: <role arn>
storageClasses:
 - name: ebs-gp3
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
   volumeBindingMode: WaitForFirstConsumer
   reclaimPolicy: Retain
   parameters:
     encrypted: "true"
     type: "gp3"
 - name: ebs-io2
   volumeBindingMode: WaitForFirstConsumer
   reclaimPolicy: Retain
   parameters:
     allowAutoIOPSPerGBIncrease: "true"
     encrypted: "true"
     iopsPerGB: "10"
     type: "io2"
```
The role arn is the result of running this CFN snippet...

```yaml
EBSDriverServiceRole:
    Type: AWS::IAM::Role
    Properties:
      # this kinda hurts me inside, but it's really he only way to parameterize keys
      AssumeRolePolicyDocument: !Sub
        - |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OIDC_PROVIDER}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${OIDC_PROVIDER}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa",
                    "${OIDC_PROVIDER}:aud": "sts.amazonaws.com"
                  }
                }
              }
            ]
          }
        - OIDC_PROVIDER: !ImportValue EKSClusterOIDCProvider
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateSnapshot
                  - ec2:AttachVolume
                  - ec2:DetachVolume
                  - ec2:ModifyVolume
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeInstances
                  - ec2:DescribeSnapshots
                  - ec2:DescribeTags
                  - ec2:DescribeVolumes
                  - ec2:DescribeVolumesModifications
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                Resource:
                  - arn:aws:ec2:*:*:volume/*
                  - arn:aws:ec2:*:*:snapshot/*
                Condition:
                  StringEquals:
                    ec2:CreateAction:
                      - CreateVolume
                      - CreateSnapshot
              - Effect: Allow
                Action:
                  - ec2:DeleteTags
                Resource:
                  - arn:aws:ec2:*:*:volume/*
                  - arn:aws:ec2:*:*:snapshot/*
              - Effect: Allow
                Action:
                  - ec2:CreateVolume
                Resource: '*'
                Condition:
                  StringLike:
                    aws:RequestTag/ebs.csi.aws.com/cluster: "true"
              - Effect: Allow
                Action:
                  - ec2:CreateVolume
                Resource: '*'
                Condition:
                  StringLike:
                    aws:RequestTag/CSIVolumeName: '*'
              - Effect: Allow
                Action:
                  - ec2:DeleteVolume
                Resource: '*'
                Condition:
                  StringLike:
                    ec2:ResourceTag/CSIVolumeName: '*'
              - Effect: Allow
                Action:
                  - ec2:DeleteVolume
                Resource: '*'
                Condition:
                  StringLike:
                    ec2:ResourceTag/ebs.csi.aws.com/cluster: "true"
              - Effect: Allow
                Action:
                  - ec2:DeleteSnapshot
                Resource: '*'
                Condition:
                  StringLike:
                    ec2:ResourceTag/CSIVolumeSnapshotName: '*'
              - Effect: Allow
                Action:
                  - ec2:DeleteSnapshot
                Resource: '*'
                Condition:
                  StringLike:
                    ec2:ResourceTag/ebs.csi.aws.com/cluster: "true"
```
