### ISSUE TITLE
[Helm Chart][Feature] Node Affinity Support For Node Pod

### ISSUE THREAD

**Issue by resec** [kubernetes-sigs/aws-ebs-csi-driver#1031]
**Is your feature request related to a problem? Please describe.**

I have hundreds of nano nodes in my cluster, and they do not need mounting volumes. As the node is very small, resource on it is precious. While there are many other types of nodes in my cluster, on which it is common to have the node pod deployed on them.

So I would like to use the affinity to exclude those nano nodes. (The same I did for some other daemonsets)

**Describe the solution you'd like in detail**

If the helm chart can support node affinity settings, then can rule out those deploying node pod into nano nodes, save lots of resources.

With below method:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: <some_exlucde_label>
          operator: DoesNotExist
```

**Describe alternatives you've considered**

Add a special label to every of existing node, so we can use a simply node selector. But it is very troublesome and every node added in the future have to contain this special label. I would like to use the "exclude", but not the "include" for easilier maintenance   

**Additional context**
