### ISSUE TITLE
No permissions to create EBS volumes if the EBS controllers are installed in all the nodes in cluster

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/aws-ebs-csi-driver#1033]
/kind feature

**What happened?**
Installed the EBS CSI driver as add-on to the AWS cluster, then tried creating the EBS volumes using statefulsets, but the statefulset pods failed to run with the below error:
`could not create volume in EC2: UnauthorizedOperation: You are not authorized to perform this operation`

**What you expected to happen?**
The volume creation should have been successful using statefulset.

**How to reproduce it (as minimally and precisely as possible)?**

1. Create AWS workload cluster.
2. Install EBS CSI driver on workload cluster using CRD manifests.
3. Create nginx service and related statefulset with volume claim and storage class. Here's the manifest I used:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-ebs-volumes
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "100"
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - us-east-1a
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx-svc"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - name: nginx-web
              containerPort: 80
          volumeMounts:
            - name: nginx-volumes
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volumes
          persistentVolumeClaim:
            claimName: nginx-volumes
  volumeClaimTemplates:
    - metadata:
        name: nginx-volumes
      spec:
        storageClassName: "aws-ebs-volumes"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi
```

**Anything else we need to know?**: We want the CSI controller deployment pinned to the control plane which should have the right permissions, the potential fix for this would be to add node affinity rules to the EBS controller deployment
```yaml
serviceAccountName: ebs-csi-controller-sa
tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
        tolerationSeconds: 300
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
```
**Environment**
- Kubernetes version (use `kubectl version`): v1.21.2
- Driver version:  master branch
