### ISSUE TITLE
EBS drive not removed from AWS when Retain policy used

### ISSUE THREAD

**Issue by vladislavPV** [kubernetes-sigs/aws-ebs-csi-driver#1071]
/kind bug

I'm running manifest bellow to get a pod with ebs gp3 drive.
The pod is starting with EBS drive and it's running fine. Next I delete manifest, so everything is gone except pv which is expected with `Retain` policy. Now , when I'm trying to remove the PV I get error, but PV is removed from K8S only. AWS still have the drive in place.

ERROR:
```
[ebs-csi-controller-7675596d88-cbrp9 csi-attacher] E0924 18:25:15.228947       1 csi_handler.go:676] Failed to remove finalizer from PV "pvc-c0863b48-cff5-4f12-8c1c-ffb2abbe7324": PersistentVolume "pvc-c0863b48-cff5-4f12-8c1c-ffb2abbe7324" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"kubernetes.io/pv-protection"}
[ebs-csi-controller-7675596d88-cbrp9 csi-attacher] I0924 18:25:15.247576       1 csi_handler.go:681] Removed finalizer from PV "pvc-c0863b48-cff5-4f12-8c1c-ffb2abbe7324"
```

MANIFEST:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain 
allowVolumeExpansion: true
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: xfs
  throughput: "1000"
  iops: "16000"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim


```

**What you expected to happen?**
EBS must be removed after PV is manually removed.

**How to reproduce it (as minimally and precisely as possible)?**
- deploy latest aws-ebs-csi-driver
- deploy manifest
- wait till pod is running
- remove manifest
- remove leftover PV
**Anything else we need to know?**:

**Environment**
- Kubernetes version 
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 1.3.0
- helm chart version: 2.3.0
