### ISSUE TITLE
Container resource requests/limits

### ISSUE THREAD

**Issue by gabegorelick** [kubernetes-sigs/aws-ebs-csi-driver#1096]
**Is your feature request related to a problem?/Why is this needed**
Out of the box, the EBS CSI driver manifests do not container any [container resource requests or limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/). You can specify container resources via the Helm chart, but it's not clear what values should be used.

/feature

**Describe the solution you'd like in detail**
Clear CPU and memory requests and limits for each container. Ideally baked into the manifests in this repo and the Helm chart, but if not that then at least documented so that they can be manually applied by users.

**Describe alternatives you've considered**

The chart provides this example, but it's not clear if those values are up to date: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/34f6146bc0353f01442739c6a019379b164bcb17/charts/aws-ebs-csi-driver/values.yaml#L103-L114

**Additional context**
A lot of linters/scanners will flag/reject containers without resource requests or limits. You also need to define resources to get into a better QoS class.

**Comment by gabegorelick** [comment]
Does EBS CSI driver resource usage vary that much that it can't provide more concrete numbers? I would think it needs a fairly static amount of resources. Or is it processing requests concurrently and thus depends on the size of the cluster?

It's also pretty standard for containers to ship with *some* guarantee as to their resource usages. E.g. https://github.com/kubernetes/autoscaler/blob/6dee2fbeff2c4ad2a104a56022789902cb5f153a/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml#L149 or https://github.com/coredns/deployment/blob/292169955ccc2d670860ac4cfc90e0fb644c55b3/kubernetes/coredns.yaml.sed#L121. In fact, I'd say it's rarer to see a container *without* any resources specified. 

It's arguably bad practice for EBS CSI driver not to ship with anything at all. I know it gets flagged by a ton of scanners. I'd argue that it should ship with some set of reasonable defaults since users can always customize it if they need to. And then if you get reports of it not working for users, it can be tweaked accordingly.

**Comment by slaterjon** [comment]
We have admission controller requirements that require there be limits and requests.  These so far have worked ok for us (granted we currently are not using many PVC's, and currently using aws-ebs-driver v0.8.1 and k8s v1.16)
`ebs-plugin:
```yaml
resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
```
csi-provisioner:
```yaml
resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
```
csi-attacher:
```yaml
resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
```
node-driver-registrar:
```yaml
resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
```
liveness-probe:
```yaml
resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 25m
              memory: 50Mi
````
