### ISSUE TITLE
Wrong role assumed by controller in v1.5.0

### ISSUE THREAD

**Issue by evindunn** [kubernetes-sigs/aws-ebs-csi-driver#1142]
/kind bug

**What happened?**
Helm install with the following values:
```yaml
image:
  repository: "public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver"
  tag: "v1.5.0"

controller:
  serviceAccount:
    create: true
    name: ebs-csi-controller-sa
    annotations:
      "eks.amazonaws.com/role-arn": "arn:aws:iam::[AccountId]:role/CSIVolumeProvisoner"
```

Causes the following logs in the controller:
```
I1216 06:45:41.487709       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-
system", Name:"ebs-claim-2", UID:"01f023d2-2722-4fdc-9627-7488555a7ed4", APIVersion:"v1", 
ResourceVersion:"209191", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with
StorageClass "gp3": rpc error: code = Internal desc = Could not create volume "pvc-01f023d2-2722-4fdc-9627-
7488555a7ed4": could not create volume in EC2: UnauthorizedOperation: You are not authorized to perform this operation.
```

And the following logs in CloudTrail:
```json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "AROA52SUST2TRSWWUGNHV:i-0669bc47163d840b5",
        "arn": "arn:aws:sts::[AccountId]:assumed-role/astro-eks-prod-node-instance/i-0669bc47163d840b5",
        "accountId": "[AccountId]",
        "accessKeyId": "[Access Key Id]",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "AROA52SUST2TRSWWUGNHV",
                "arn": "arn:aws:iam::[Account Id]:role/astro-eks-prod-node-instance",
                "accountId": "[Account Id]",
                "userName": "astro-eks-prod-node-instance"
            },
            "webIdFederationData": {},
            "attributes": {
                "creationDate": "2021-12-16T06:17:48Z",
                "mfaAuthenticated": "false"
            },
            "ec2RoleDelivery": "2.0"
        }
    },
    "eventTime": "2021-12-16T06:41:25Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "CreateVolume",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "[Source IP]",
    "userAgent": "aws-sdk-go/1.40.4 (go1.17.5; linux; amd64) exec-env/aws-ebs-csi-driver-v1.5.0",
    "errorCode": "Client.UnauthorizedOperation",
    "errorMessage": "You are not authorized to perform this operation. Encoded authorization failure message:  [Encoded message]",
    "requestParameters": {
        "size": "256",
        "zone": "us-west-2b",
        "volumeType": "gp3",
        "encrypted": false,
        "tagSpecificationSet": {
            "items": [
                {
                    "resourceType": "volume",
                    "tags": [
                        {
                            "key": "kubernetes.io/created-for/pvc/namespace",
                            "value": "kube-system"
                        },
                        {
                            "key": "kubernetes.io/created-for/pv/name",
                            "value": "pvc-01f023d2-2722-4fdc-9627-7488555a7ed4"
                        },
                        {
                            "key": "ebs.csi.aws.com/cluster",
                            "value": "true"
                        },
                        {
                            "key": "CSIVolumeName",
                            "value": "pvc-01f023d2-2722-4fdc-9627-7488555a7ed4"
                        },
                        {
                            "key": "kubernetes.io/created-for/pvc/name",
                            "value": "ebs-claim-2"
                        }
                    ]
                }
            ]
        },
        "clientToken": "[Client Token]"
    },
    "responseElements": null,
    "requestID": "efc4c304-a246-4c4f-808a-c9966614e91d",
    "eventID": "9f4d947f-38ed-43f1-9fe3-0206b334a3a5",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "[Account Id]",
    "eventCategory": "Management"
}
```

It looks like the controller is assuming `arn:aws:iam::[Account Id]:role/astro-eks-prod-node-instance`, the node instance role, instead of `arn:aws:iam::[AccountId]:role/CSIVolumeProvisoner`, the provisioner role?

**What you expected to happen?**
Volume is created successfully

**How to reproduce it (as minimally and precisely as possible)?**
1. Create `arn:aws:iam::[AccountId]:role/CSIVolumeProvisoner` with recommended IAM policy in this repo
2. Install with helm values above
3. Create pvc + pod

**Anything else we need to know?**:
Reverting to v1.4.0 with the following values provisions volumes as expected
```yaml
image:
  # Our region is us-west-2
  repository: "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver"
  tag: "v1.4.0"

controller:
  serviceAccount:
    create: true
    name: ebs-csi-controller-sa
    annotations:
      "eks.amazonaws.com/role-arn": "arn:aws:iam::[Account Id]:role/CSIVolumeProvisoner"
```

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: v1.5.0
