### ISSUE TITLE
volume-attach-limit argument doesn't work in 1.20

### ISSUE THREAD

**Issue by sultanovich** [kubernetes-sigs/aws-ebs-csi-driver#1174]
/triage support

**What happened?**

Since K8s keeps trying to add volumes when it reaches the limit allowed by the AWS instance, try using the `volume-attach-limit` [argument](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#driver-options) to find a workaround while troubleshooting.

**How to reproduce it (as minimally and precisely as possible)?**

It is possible to reproduce by setting the argument and trying to create more volumes than the maximum configured as seen in the following example.

```
Name:                   ebs-csi-controller
Namespace:              kube-system
CreationTimestamp:      Mon, 07 Jun 2021 06:31:13 +0000
Labels:                 app.kubernetes.io/name=aws-ebs-csi-driver
Annotations:            deployment.kubernetes.io/revision: 8
Selector:               app=ebs-csi-controller,app.kubernetes.io/name=aws-ebs-csi-driver
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=ebs-csi-controller
                    app.kubernetes.io/name=aws-ebs-csi-driver
  Service Account:  ebs-csi-controller-sa
  Containers:
   ebs-plugin:
    Image:      k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.0.0
    Port:       9808/TCP
    Host Port:  0/TCP
    Args:
      --endpoint=$(CSI_ENDPOINT)
      --logtostderr
      --v=2
      --k8s-tag-cluster-id=cloud-dev-cluster-mix
      --volume-attach-limit=10
```

**Environment**

Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.7", GitCommit:"bfb38f707bc4a8edfcd73472ec3d96b500b8b781", GitTreeState:"clean", BuildDate:"2020-08-12T20:27:48Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

CSI-EBS Driver Version:
```
[sulta@dev [~] 14:08:21 ~] $ kubectl --kubeconfig=/home/centos/dev.kube -n kube-system describe deployments ebs-csi-controller | grep Image:
    Image:      k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.0.0
    Image:      k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
    Image:      k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
    Image:      k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
    Image:      k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
    Image:      k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
[sulta@dev [~] 14:08:27 ~] $
```

**Previous consultation without solution in the slack channel**
[https://kubernetes.slack.com/archives/C09NXKJKA/p1645218261237229](https://kubernetes.slack.com/archives/C09NXKJKA/p1645218261237229)

**Comment by sultanovich** [comment]
@k8s-ci-robot help

Keep checking the repository and I have verified that there is an example indicating that the `volume-attach-limit` argument should be located in the [ebs-plugin container section](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/271046d1be7507cc21717dbaf96e62d3de235700/charts/aws-ebs-csi-driver/templates/node.yaml#L67), as I have tried to do in my tests.


```
      containers:
        - name: ebs-plugin
          securityContext:
            privileged: true
          image: {{ printf "%s:%s" .Values.image.repository (default (printf "v%s" .Chart.AppVersion) (toString .Values.image.tag)) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - node
            - --endpoint=$(CSI_ENDPOINT)
            {{- with .Values.node.volumeAttachLimit }}
            - --volume-attach-limit={{ . }}
            {{- end }}
            - --logtostderr
            - --v={{ .Values.node.logLevel }}
```

Any idea why this argument didn't work?
