### ISSUE TITLE
stuck at resizing volume

### ISSUE THREAD

**Issue by rahulbreezo** [kubernetes-sigs/aws-ebs-csi-driver#1186]
/kind bug

**What happened?**

I created a storage class like this:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-csi-aws-com
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
parameters:
  type: io2
  iopsPerGB: '200'

```
used it like this:

```
      dataVolumeClaimSpec:
        accessModes:
          - 'ReadWriteOnce'
        # Adding io2 storage class
        storageClassName: ebs-csi-aws-com
        resources:
          requests:
            storage: 40Gi
```
resizing worked , I tried once before, 

but when I tried last time and increased storage from 40g to 60g , while volume was used upto 20 GB, 

It did not work,  volume did not increase but there was no error log either as per k8s dashboard `events` tab.

I only got this in `events` tab

`External resizer is resizing volume pvc-4c03b314-feb7-4eb9-927f-035129d93614
`

This message continuously coming from last 15 hours(since lst deployment).

 

**What you expected to happen?**

volume should have been increase to 60g

**How to reproduce it (as minimally and precisely as possible)?**

- Create storage class and PVC as I posted above, 

- fill volume upto 20GB, now try to resize. 

**Anything else we need to know?**:

I am using PGO template for postgres and giving  it PVC using this driver,
deploying driver through menifests

**Environment**
- Kubernetes version : client 1.21
- Driver version: v1.5.0

**UPDATE**

Just checked log at the right place this is the issue:

`E0311 09:06:01.481978 1 driver.go:119] GRPC error: rpc error: code = Internal desc = Could not resize volume "vol-086f444ed5cb6567e": could not modify AWS volume "vol-086f444ed5cb6567e": InvalidParameterValue: vol-086f444ed5cb6567e is an io2 Block Express volume. Size or IOPs modification is not currently supported for io2 Block Express volumes.`
