### ISSUE TITLE
pvc.spec.selector not supported

### ISSUE THREAD

**Issue by achetronic** [kubernetes-sigs/aws-ebs-csi-driver#1200]
/kind bug

**What happened?**
The standard `selector` field is not supported yet
https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/#LabelSelector

**What you expected to happen?**
To be able to put selectos on my PVCs

**How to reproduce it (as minimally and precisely as possible)?**
Just applying a PVC with `spec.selector.matchLabels`

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): EKS 1.21
- Driver version: v1.5.1

**Comment by torredil** [comment]
Can you provide more details regarding use case? Also, if possible please provide your PVC manifest, thanks.

**Comment by achetronic** [comment]
Hello there, sorry for the delay on answering,
The point is that [this exact case](https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/selector_label_binding.html) can not be used with AWS EBS CSI driver because when you try to use it the status says it is not supported, but this is a standard feature for PVCs to be able to select always the sale PVs using the LabelSelectos on the PVC.

Are you planning to support this?

**Comment by torredil** [comment]
Hi, this is currently expected behavior. From previous discussions in the K8S community and [documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#:~:text=Note%3A%20Currently%2C%20a%20PVC%20with%20a%20non%2Dempty%20selector%20can%27t%20have%20a%20PV%20dynamically%20provisioned%20for%20it.): A PVC with a non-empty selector can't have a PV dynamically provisioned for it.

**Comment by achetronic** [comment]
> Hi, this is currently expected behavior. From previous discussions in the K8S community and [documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#:~:text=Note%3A%20Currently%2C%20a%20PVC%20with%20a%20non%2Dempty%20selector%20can%27t%20have%20a%20PV%20dynamically%20provisioned%20for%20it.): A PVC with a non-empty selector can't have a PV dynamically provisioned for it. 

Hi @torredil the point is to use a PVC with selectors and without any othet parameter, right? tomorrow I will test the cases and give you some feedback about this 👨‍💻

**Comment by torredil** [comment]
@cpawlyszyn Hey thanks for providing more details on the workflow. I'd appreciate if you could send over the mock-up config and I'll take a look.

**Comment by cpawlyszyn** [comment]
@torredil I went back through my testing and found that it was an error on my part that led to the failure to bind. Here are the working YAMLs and workflow that confirmed this behavior is functional as-expected.

Application YAML:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-ss
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: busybox
  serviceName: busybox-svc
  template:
    metadata:
      labels:
        app: busybox
      name: busybox
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - sleep 9999
        image: busybox
        imagePullPolicy: Always
        name: main-container
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: busybox-data-volume
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: busybox-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
      storageClassName: gp3-backups
      volumeMode: Filesystem
```

StorageClass YAML:
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-backups
parameters:
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

Deletion/patching kubectl commands:
```shell
kubectl delete statefulset/busybox-ss -n test
kubectl delete pvc/busybox-data-volume -n test
kubectl patch pv/<PV_ID> -p '{"spec":{"claimRef": null}}'
kubectl label pv/<PV_ID> purpose=backups
```

Application YAML with label selectors on PVC:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-ss
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: busybox
  serviceName: busybox-svc
  template:
    metadata:
      labels:
        app: busybox
      name: busybox
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - sleep 9999
        image: busybox
        imagePullPolicy: Always
        name: main-container
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: busybox-data-volume
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: busybox-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
      selector:
        matchLabels:
          purpose: backups
      storageClassName: gp3-backups
      volumeMode: Filesystem
```

**Comment by torredil** [comment]
@cpawlyszyn Glad to hear you were able to get it working. Thanks for the additional insight :)

**Comment by torredil** [comment]
@achetronic Hey, wanted to check in on this again. To be clear: this is supported. One thing to look out for is the fact that K8s uses a default `StorageClass` when it's not specified, so you would have to [patch the default](https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/#changing-the-default-storageclass) `StorageClass` in the cluster to explicitly use the given PV and PVC configuration.

- `pv.yaml`
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    volume-type: ssd
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-03c604538dd7d2f41
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-east-2c
```

- `claim.yaml`

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume-type: ssd
```

- `kubectl apply -f claim.yaml && kubectl apply -f pv.yaml`
```
persistentvolumeclaim/ebs-claim created
persistentvolume/test-pv created
```

- `kubectl get pv`

```
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   REASON   AGE
test-pv   5Gi        RWO            Retain           Bound    default/ebs-claim                           20s
```

- `kubectl get pvc`

```
NAME        STATUS   VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ebs-claim   Bound    test-pv   5Gi        RWO                           37s
```
