### ISSUE TITLE
Support RAID of multiple EBS volumes

### ISSUE THREAD

**Issue by sebgl** [kubernetes-sigs/aws-ebs-csi-driver#1220]
One way to get better performance out of EBS volumes is to rely on RAIDs made of multiple EBS volumes, as described here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/raid-config.html

A common use case for example would be to build a RAID out of two st1 or sc1 volumes, which provides different performance/price characteristics than e.g. using gp3 volumes.

Unfortunately, that's not trivial in Kubernetes, as it natively expects that one mounted volume maps to a single PersistentVolume.
It seems technically possible to do the following, for example in a privileged init container:
- unmount the 2 EBS volumes that were mounted and formatted by the EBS CSI driver
- assemble a RAID with mmap, and format the resulting file system
In the main container, the RAID volume can then be mounted through a hostPath.

While it can technically work, it's not enough, as it does not ensure the lifecycle of the resulting volume:
- the RAID volume should be unmounted if the Pod is deleted
- accessing the same RAID volume from another host should be possible
- resizing the RAID volume up

I think this should be better handled by the EBS CSI driver directly, and abstracted away from end-users.
Users would for example declare the following storage class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc1-raid
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: sc1
  raid:
    type: 0
    volumeCount: 3
```

and the following PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc1-raid
  resources:
    requests:
      storage: 300Gi
```

As a result, the driver would provision 3 sc1 volumes of 100Gi each (`PVC storage requests / storage class volume count`, rounded up), build the RAID, and create one resulting PersistentVolume that can be bound to that claim. From the user perspective there is a single 300Gi volume, the way the RAID is manipulated is not the user's concern.
