### ISSUE TITLE
Can't colone volume from snapshot.

### ISSUE THREAD

**Issue by skrbug** [kubernetes-sigs/aws-ebs-csi-driver#1253]
/triage support
**What happened?**
I created a pvc reference by cloning the volume from snapshot and mounted it to the pod nginx, but the nginx pod has no mounted data. 
Here is my yaml files.  

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filecoin-calibration-snapshot-claim-case1
  namespace: web3-helm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 33Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: filecoin-calibration-snapshot
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: web3-helm
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /test-snapshot
      name: snapshot-data
  volumes:
  - name: snapshot-data
    persistentVolumeClaim:
      claimName: filecoin-calibration-snapshot-claim-case1
```

Debug Trace
```
kubectl get pvc -n web3-helm
filecoin-calibration-snapshot-claim-case1                     Bound    pvc-1574f7c9-da3b-4498-b27a-d127b4031fef   33Gi       RWO            gp2            78s
```

Check how csi-node handles. 
```
kubectl logs -n kube-system ebs-csi-node-qdrwd  -c ebs-plugin  | grep "pvc-1574f7c9-da3b-4498-b27a-d127b4031fef"
I0530 11:19:50.127958       1 mount_linux.go:453] Disk successfully formatted (mkfs): ext4 - /dev/nvme7n1 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1574f7c9-da3b-4498-b27a-d127b4031fef/globalmount
```

I'm guessing it's formatted so data is lost, but why is it formatted？

**Env**
```
kubectl version
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

helm ls -n kube-system
NAME                           	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                   	APP VERSION
aws-ebs-csi-driver-2-1652871123	kube-system	2       	2022-05-20 12:35:08.816660196 +0000 UTC	deployed	aws-ebs-csi-driver-2.6.7	1.6.1
```
