### ISSUE TITLE
Support tagSpecification on VolumeSnapshotClass

### ISSUE THREAD

**Issue by achetronic** [kubernetes-sigs/aws-ebs-csi-driver#1261]
/kind bug

**What happened?**
The tagSpecification for StorageClass is not being applied on VolumeSnapshotClass as expected

**What you expected to happen?**
The same tags applied to the PV, being populated to the Snapshots because it is useful to know contextual information about where the snapshot came from. 

**How to reproduce it (as minimally and precisely as possible)?**

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-block
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
parameters:
  tagSpecification_1: "pvcnamespace={{ .PVCNamespace }}"
  tagSpecification_2: "pvcname={{ .PVCName }}"
  tagSpecification_3: "pvname={{ .PVName }}"
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-14c7a48", GitCommit:"717bfb2b8ceb809a42a6c0baabde59fae28637ef", GitTreeState:"clean", BuildDate:"2022-04-01T03:17:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: v1.6.1
