### ISSUE TITLE
default kmsKeyID is not used when value is null

### ISSUE THREAD

**Issue by amilanoski** [kubernetes-sigs/aws-ebs-csi-driver#1267]
/kind bug

**What happened?**
default kmskeyid is not used even though CMK is set in EC2 Dashboard >EBS Encryption 

**What you expected to happen?**

For aws-csi-driver to use the default CMK kms key when set in the aws console.

**How to reproduce it (as minimally and precisely as possible)?**
values.yaml 
```
storageClasses:
# Add StorageClass resources like:
- name: ebs-sc
  # annotation metadata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  # label metadata
  # labels:
  #   my-label-is: supercool
  # defaults to WaitForFirstConsumer
  volumeBindingMode: WaitForFirstConsumer
  # defaults to Delete
  reclaimPolicy: Delete
  parameters:
    encrypted: "true"
  allowVolumeExpansion: true
```

**Anything else we need to know?**:
kms key is set to the aws generated kms key rather then the CMK we have created.

only work around is to set the kmskeyid to the arn we require.  Either the docs need to be updated or there is a bug.  I am not sure.  Hoping for some guidance and answers. Thanks in advance. 

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:  helm chart version: 2.6.3

**Comment by torredil** [comment]
This is not a bug and currently expected behavior. To clarify: Amazon EBS automatically creates a unique AWS managed key in each Region where you store AWS resources. This [KMS key](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#:~:text=Amazon%20EBS%20automatically%20creates%20a%20unique%20AWS%20managed%20key%20in%20each%20Region%20where%20you%20store%20AWS%20resources.%20This%20KMS%20key%20has%20the%20alias%20alias/aws/ebs.%20By%20default%2C%20Amazon%20EBS%20uses%20this%20KMS%20key%20for%20encryption.) has the alias alias `/aws/ebs`. By default, Amazon EBS uses this KMS key for encryption. 

If you wish to use a different kms key, you **must** specify it in the StorageClass. If the encrypted parameter is set to "true" but no key is specified, the AWS generated kms key will be used by default.

**Comment by amilanoski** [comment]
Thanks for confirming @torredil and updating the docs. I have tested some different paths with default EBS CMK configured in the console.

option 1 - **values.yaml  - encryption:true**
```
storageClasses:
# Add StorageClass resources like:
- name: ebs-sc
  # annotation metadata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  # label metadata
  # labels:
  #   my-label-is: supercool
  # defaults to WaitForFirstConsumer
  volumeBindingMode: WaitForFirstConsumer
  # defaults to Delete
  reclaimPolicy: Delete
  parameters:
    encrypted: "true"
  allowVolumeExpansion: true
```

option 2 -  **values.yaml - no encryption set**
```
storageClasses:
# Add StorageClass resources like:
- name: ebs-sc
  # annotation metadata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  # label metadata
  # labels:
  #   my-label-is: supercool
  # defaults to WaitForFirstConsumer
  volumeBindingMode: WaitForFirstConsumer
  # defaults to Delete
  reclaimPolicy: Delete
  # parameters:
  #   encrypted: "true"
  allowVolumeExpansion: true
```

option 3 -  **values.yaml - encryption set + kmskeyid**
```
storageClasses:
# Add StorageClass resources like:
- name: ebs-sc
  # annotation metadata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  # label metadata
  # labels:
  #   my-label-is: supercool
  # defaults to WaitForFirstConsumer
  volumeBindingMode: WaitForFirstConsumer
  # defaults to Delete
  reclaimPolicy: Delete
  parameters:
    encrypted: "true"
    kmsKeyId: "arn:xxxxx"
  allowVolumeExpansion: true
```
Results:

1.  aws-csi-driver will encrypted the drive, but with aws managed kms key(which seems to be expected)
2. aws-csi-driver will encrypted the drive and using the default EBS encryption key specified in the console.(the behaviour I was expecting)
3. aws-csi-driver encrypted EBS volume with kmsKeyID as expected(expected)

Do you think docs should be updated, so that users who have a custom default EBS CMK set to not set **parameters.encrypted** or **parameters.kmsKeyId** ?
