### ISSUE TITLE
Race condition with volume attach limits when new node joins the cluster leads to oversubscribed node

### ISSUE THREAD

**Issue by steved** [kubernetes-sigs/aws-ebs-csi-driver#1278]
/kind bug

**What happened?**

I believe this is similar to #1163 (and perhaps even #1258), but distinct enough that I thought it warranted another issue. This may also be the wrong repository, I just encountered it specifically with EKS and the aws-ebs-csi-driver.

When a cluster is scaled up in response to new pods with PVCs and a custom `volume-attach-limit` is set, somehow the restriction is not enforced happens leading to all pods being scheduled.

**What you expected to happen?**

Ideally, only the pods that can fit the volume attach limit can be scheduled to the node. I'm unsure if this is something that needs to happen in the [Kubernetes nodevolumes filter](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go), however.

**How to reproduce it (as minimally and precisely as possible)?**

1. Create a cluster with aws-ebs-csi-driver and cluster-autoscaler deployed and a node pool (`node-pool: my-node-pool`) for other pods
2. Set `--volume-attach-limit=5` on the node driver
3. Create a statefulset similar to
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vols-pv-test
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: vols-pv-test
  replicas: 10
  template:
    metadata:
      labels:
        app: vols-pv-test
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.5
        volumeMounts:
        - name: test-volume
          mountPath: /test
      nodeSelector:
        node-pool: "my-node-pool"
  volumeClaimTemplates:
  - metadata:
      name: test-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mystorageclass"
      resources:
        requests:
          storage: 1Gi
```
4. All 10 pods are scheduled on the newly created node even with the attach limit

If I then delete all the pods, only 5 will reschedule to the same node and the other 5 will wait for a new autoscaled node. This issue still occurs even if the PVCs are already provisioned.

**Anything else we need to know?**:
_N/A_

**Environment**
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`
- Driver version: 1.5.3
