### ISSUE TITLE
2.8.1 release fails to pull containers

### ISSUE THREAD

**Issue by Setheck** [kubernetes-sigs/aws-ebs-csi-driver#1311]
/kind bug

**What happened?**
Helm auto upgraded from 2.8.0 to 2.8.1 and containers pulls failed

**What you expected to happen?**
Successful helm upgrade

**How to reproduce it (as minimally and precisely as possible)?**
I guess install the v2.8.1 helm chart?

**Anything else we need to know?**:
Nope

**Environment**
- Kubernetes version (use `kubectl version`):  eks v 1.22
- Driver version: 2.8.1

**Comment by torredil** [comment]
Hey thanks for raising this up, is there a specific container that is failing? Helm chart `v2.8.1` pulls container images as follows:
```
image:
  repository: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver
  tag: ""
  
sidecars:
  provisioner:
    image:
      repository: k8s.gcr.io/sig-storage/csi-provisioner
      tag: "v3.1.0"
  attacher:
    image:
      repository: k8s.gcr.io/sig-storage/csi-attacher
      tag: "v3.4.0"
  snapshotter:
    image:
      repository: k8s.gcr.io/sig-storage/csi-snapshotter
      tag: "v6.0.1"
  livenessProbe:
    image:
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: "v2.6.0"
  resizer:
    image:
      repository: k8s.gcr.io/sig-storage/csi-resizer
      tag: "v1.4.0"
  nodeDriverRegistrar:
    image:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: "v2.5.1"
``` 
Verified all images listed above are present in the corresponding registry and driver installation with Helm chart  `v2.8.1` works:

- `Install CSI driver v1.9.0 using Helm chart v2.8.1`

```
$ helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver

$ helm repo update

$ helm upgrade --install aws-ebs-csi-driver \
    --namespace kube-system \
    aws-ebs-csi-driver/aws-ebs-csi-driver
```

- `kubectl describe deployment ebs-csi-controller -n kube-system`

```            
Name:                   ebs-csi-controller
Namespace:              kube-system
CreationTimestamp:      Wed, 13 Jul 2022 16:19:18 +0000
Labels:                 app.kubernetes.io/component=csi-driver
                        app.kubernetes.io/instance=aws-ebs-csi-driver
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=aws-ebs-csi-driver
                        app.kubernetes.io/version=1.9.0
                        helm.sh/chart=aws-ebs-csi-driver-2.8.1
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: aws-ebs-csi-driver
                        meta.helm.sh/release-namespace: kube-system
Selector:               app=ebs-csi-controller,app.kubernetes.io/instance=aws-ebs-csi-driver,app.kubernetes.io/name=aws-ebs-csi-driver
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=ebs-csi-controller
                    app.kubernetes.io/component=csi-driver
                    app.kubernetes.io/instance=aws-ebs-csi-driver
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=aws-ebs-csi-driver
                    app.kubernetes.io/version=1.9.0
                    helm.sh/chart=aws-ebs-csi-driver-2.8.1
  Service Account:  ebs-csi-controller-sa
  Containers:
   ebs-plugin:
    Image:      public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.9.0
    Port:       9808/TCP
    Host Port:  0/TCP
    Args:
      controller
      --endpoint=$(CSI_ENDPOINT)
      --logtostderr
      --v=2
    Liveness:   http-get http://:healthz/healthz delay=10s timeout=3s period=10s #success=1 #failure=5
    Readiness:  http-get http://:healthz/healthz delay=10s timeout=3s period=10s #success=1 #failure=5
    Environment:
      CSI_ENDPOINT:           unix:///var/lib/csi/sockets/pluginproxy/csi.sock
      CSI_NODE_NAME:           (v1:spec.nodeName)
      AWS_ACCESS_KEY_ID:      <set to the key 'key_id' in secret 'aws-secret'>      Optional: true
      AWS_SECRET_ACCESS_KEY:  <set to the key 'access_key' in secret 'aws-secret'>  Optional: true
      AWS_EC2_ENDPOINT:       <set to the key 'endpoint' of config map 'aws-meta'>  Optional: true
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
   csi-provisioner:
    Image:      k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=2
      --feature-gates=Topology=true
      --extra-create-metadata
      --leader-election=true
      --default-fstype=ext4
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
   csi-attacher:
    Image:      k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=2
      --leader-election=true
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
   csi-resizer:
    Image:      k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=2
      --handle-volume-inuse-error=false
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
   liveness-probe:
    Image:      k8s.gcr.io/sig-storage/livenessprobe:v2.6.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-address=/csi/csi.sock
    Environment:  <none>
    Mounts:
      /csi from socket-dir (rw)
  Volumes:
   socket-dir:
    Type:               EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:          <unset>
  Priority Class Name:  system-cluster-critical
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   ebs-csi-controller-5bd949bccb (2/2 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  2m3s  deployment-controller  Scaled up replica set ebs-csi-controller-5bd949bccb to 2
```
