### ISSUE TITLE
Provide a way to copy labels from pvc to pv

### ISSUE THREAD

**Issue by speedfl** [kubernetes-sigs/aws-ebs-csi-driver#1320]
**Is your feature request related to a problem?/Why is this needed**

As a user I want to be able to have a selection of label copied from my pvc to my pv when using a StorageClass. This will allow to rapidly identify the purpose of the PV created (environment, project)

When using Kubecost for example, it would allow to better filter the assets and generate reports.

/feature

**Describe the solution you'd like in detail**
Similar to tagSpecification feature https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1190

It could be easy to introduce a field `copyLabel_n`. Example:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 
  copyLabel_1: "my.organization/environment"
  copyLabel_2: "my.organization/customer"
  copyLabel_3: "my.organization/billing-id"
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
