### ISSUE TITLE
csi-provisioner is using wrong api endpoint for CSINode call

### ISSUE THREAD

**Issue by jbasement** [kubernetes-sigs/aws-ebs-csi-driver#1336]
/kind bug

**What happened?**
I'm trying to create a PVC based on an SC with `volumeBindingMode: WaitForFirstConsumer` set. Previously I had `--feature-gates=Topology` set to false, which then resulted in the PVC getting created in the wrong zone. 
That's why I set  `--feature-gates=Topology=true` on the csi-provisioner. But now the csi-provisioner throws this error 

`reflector.go:127] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSINode: failed to list *v1.CSINode: the server could not find the requested resource` 

and the PVC is stuck in pending with the following message 
`persistentvolume-controller waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator`.

After investigating the issue I bit I think I stumbled upon the issue. The CSINode resources on our cluster are using `apiVersion: storage.k8s.io/v1beta1` but the csi-provisioner is trying to call `*v1.CSINode` that's why it can't find the resource on the API server, because it should try to reach them on `v1beta1` instead of `v1`. 
The official Kubernetes[ featureGate documentation ](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) also has `CSINodeInfo` listed as Beta on k8s v1.16.

**What do you expect to happen?**
The PVC gets created in the same zone as the pod. And the csi-provisioner can list CSINode without an error.

**How to reproduce it (as minimally and precisely as possible)?**
1. Create SC 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-test
reclaimPolicy: Delete
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "false"
```
2. Create PVC and Pod
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-test
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

3. `--feature-gates=Topology` set on csi-provisioner
4. Also same k8s and aws-ebs-csi-driver version as mentioned below as both are a bit outdated

**Anything else we need to know?**:

We're currently forced to use aws-ebs-csi-driver v0.8.2 as we are stuck on Kubernetes version 1.16. I'm sure this might probably be fixed in a later version already but that's what we currently have to work with.
Also all required featureGates are set on the kube api server and the kubelet(s).

**Environment**
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14", GitCommit:"d2a081c8e14e21e28fe5bdfa38a817ef9c0bb8e3", GitTreeState:"clean", BuildDate:"2020-08-13T12:24:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
Repo version used on helm chart v0.8.2
aws-ebs-csi-driver: v0.8.1
csi-provisioner: v2.0.2
