### ISSUE TITLE
Support fixed number of IOPs for IO2 Volumes 

### ISSUE THREAD

**Issue by dschunack** [kubernetes-sigs/aws-ebs-csi-driver#1364]
/kind bug

**What happened?**
Hi,

We want to create IO2 Volumes with a fixed number of IOPs. In our Case 4000, but this failed.

```yaml
  Warning  ProvisioningFailed    11s (x5 over 26s)  ebs.csi.aws.com_ebs-csi-controller-5dffb85b48-vvfd7_adbcc48b-3c9b-469c-82e3-0ffa30ad9abe  failed to provision volume with StorageClass "linux-ext4-io2-4000-iops-ebs-csi-encrypted": rpc error: code = Internal desc = Could not create volume "pvc-c66ca278-cdea-43f2-809b-60ab093ff4b8": invalid combination of volume size 10 GB and iopsPerGB 0: the resulting IOPS 0 is too low for AWS, it must be at least 100
```

Look like this is not supported yet for IO2 Volumes as it is for GP3 Volumes.

IO2:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/c05f2f8f2c0db46e35e4984091c6ed403a2b43d4/pkg/cloud/cloud.go#L297

GP3:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/c05f2f8f2c0db46e35e4984091c6ed403a2b43d4/pkg/cloud/cloud.go#L303

**What you expected to happen?**

A new IO2 Volume with the defined number of IOPs 

**How to reproduce it (as minimally and precisely as possible)?**

IO2 StorageClass

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    fstype: ext4
    kubernetes.io/os: linux
    type: io2
  name: test-io2-4000-iops
parameters:
  csi.storage.k8s.io/fstype: ext4
  encrypted: "true"
  iops: "4000"
  type: io2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
allowVolumeExpansion: true
```

Create a PVC

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: default
spec:
  storageClassName: "test-io2-4000-iops"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): EKS 1.23
- Driver version: v1.11.2
