### ISSUE TITLE
Helm chart upgrade 2.11.1 --> 2.12.0 removes entire deployment.

### ISSUE THREAD

**Issue by mhobbs812** [kubernetes-sigs/aws-ebs-csi-driver#1415]
/kind bug

**What happened?**
All the components related the aws-ebs-csi driver provider by the helm chart are gone.

**What you expected to happen?**
I expect to be able to track the major version of the helm chart. Now everything deployed in my cluster is b0rked because it can't use EBS.

**How to reproduce it (as minimally and precisely as possible)?**
Not sure yet, still trying to determine what actually happened.

**Anything else we need to know?**:
Values for the helm chart are minimal, we mostly use the defaults.
```
  values:
    controller:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/irsa-ebs
  
```

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.10-eks-15b7512
```

- Driver version:
Can't say seeing as nothing is deployed anymore
