### ISSUE TITLE
 unattached volumes=[persistent-storage default-token-zcptq]: timed out waiting for the condition

### ISSUE THREAD

**Issue by kbsonlong** [kubernetes-sigs/aws-ebs-csi-driver#1437]
/kind bug

**What happened?**
driver.go:120] GRPC error: rpc error: code = Internal desc = Failed to find device path /dev/xvdba. 
Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage default-token-zcptq]: timed out waiting for the condition

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**
```yaml
cat << EOF | kubectl apply -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
EOF
```

**Anything else we need to know?**:
```bash
helm upgrade --install aws-ebs-csi-driver \
    --namespace kube-system \
    aws-ebs-csi-driver/aws-ebs-csi-driver \
    --set node.kubeletPath=/data/k8s/kubelet
```

![image](https://user-images.githubusercontent.com/23339284/199167731-4115263c-c4ec-4091-9da5-a8f16b855230.png)

```bash
# kubectl get pvc ebs-claim  
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ebs-claim   Bound    pvc-e358a798-28fe-4647-9654-8830b36dbfc5   4Gi        RWO            ebs-sc         30m
# kubectl describe pvc ebs-claim  
Name:          ebs-claim
Namespace:     default
StorageClass:  ebs-sc
Status:        Bound
Volume:        pvc-e358a798-28fe-4647-9654-8830b36dbfc5
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: shopline-xinjiapo-aws-dev-vm-8c32g-600g-10-86-183-104
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      4Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       app
Events:
  Type    Reason                 Age                From                                                                                     Message
  ----    ------                 ----               ----                                                                                     -------
  Normal  WaitForFirstConsumer   30m                persistentvolume-controller                                                              waiting for first consumer to be created before binding
  Normal  Provisioning           30m                ebs.csi.aws.com_ebs-csi-controller-5cbfd45dc-m8pfp_e17d0a57-8b67-4568-a69b-28e609f2909e  External provisioner is provisioning volume for claim "default/ebs-claim"
  Normal  ExternalProvisioning   30m (x2 over 30m)  persistentvolume-controller                                                              waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
  Normal  ProvisioningSucceeded  30m                ebs.csi.aws.com_ebs-csi-controller-5cbfd45dc-m8pfp_e17d0a57-8b67-4568-a69b-28e609f2909e  Successfully provisioned volume pvc-e358a798-28fe-4647-9654-8830b36dbfc5


```

**Environment**
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
aws-ebs-csi-driver:v1.12.1

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1437#tasklist-block-7a8c8c1e-8c72-4c37-b7a2-0ca80156a588
