### ISSUE TITLE
Helm: Allow to set custom secret name & keys

### ISSUE THREAD

**Issue by der-eismann** [kubernetes-sigs/aws-ebs-csi-driver#1492]
**Is your feature request related to a problem?/Why is this needed**
We use helm to install the EBS driver on our cluster. However the default secret name `aws-secret` is so generic and can't be changed atm, which makes it hard to use on a larger cluster. Would be nice if one could change the name of the secret and its keys.

/feature

**Describe the solution you'd like in detail**
```
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.controller.aws_access_key.secret_name }}
                  key: {{ .Values.controller.aws_access_key.key_for_id }}
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.controller.aws_access_key.secret_name }}
                  key: {{ .Values.controller.aws_access_key.key_for_secret }}
                  optional: true
```
