### ISSUE TITLE
Helm-Chart configuration option for volumeLifecycleModes, podInfoOnMount

### ISSUE THREAD

**Issue by haarchri** [kubernetes-sigs/aws-ebs-csi-driver#1524]
**Is your feature request related to a problem?/Why is this needed**
today its not possible in helm-chart to configure `volumeLifecycleModes` and `podInfoOnMount` we need this feature for Inline EphemeralStorageRequests when ex. AWS EC2 Instances with low storage only available 

https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/596-csi-inline-volumes/README.md#support-for-inline-csi-volumes

https://kubernetes-csi.github.io/docs/csi-driver-object.html#what-fields-does-the-csidriver-object-have

the bad thing is that `volumeLifecycleModes` and `podInfoOnMount` are immutable fields - so its not possible to update a csiDriver :/

**Describe the solution you'd like in detail**
`volumeLifecycleModes` and `podInfoOnMount` configurable in aws-ebs-csi-driver helm-chart

**Additional context**
without the `volumeLifecycleModes` set to `Ephemeral` all Inline EphemeralStorageRequests will created and not removed after pod lifecycle which leads in hundreds of PVCs

```
kubectl get pvc -n xxxx  | grep -e "build-" | awk {'print $1'} | wc -l
    1350
```

![image](https://user-images.githubusercontent.com/21083497/223410523-d14c54fe-4ed0-4379-a73b-f3db3944e04c.png)

**Comment by bryantbiggs** [comment]
@haarchri I believe you are using [generic ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) and not [CSI ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volumes) (also called [ephemeral Inline CSI volumes](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/596-csi-inline-volumes#kep-596-ephemeral-inline-csi-volumes)) from the manifest snippet posted.

Using the simple deployment below, I was able to scale up the deployment and verify the ephemeral volumes are mounted to the pods, and then scale down and verify the EBS volumes are cleaned up:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-dep
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
        - name: my-dep
          image: public.ecr.aws/amazonlinux/amazonlinux:2
          volumeMounts:
          - mountPath: "/scratch"
            name: scratch
          command: ["sleep", "1000000"]
      volumes:
        - name: scratch
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: my-dep
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: gp2
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 1Gi
```

Versions:
EKS - `1.27`
EBS CSI driver - `v1.21.0-eksbuild.1`

Let me know if you have any additional details related to your setup, I'd be happy to take a look to try to reproduce
