### ISSUE TITLE
EBS snapshots are not getting created using csi-snapshotter sidecar

### ISSUE THREAD

**Issue by hussain2109** [kubernetes-sigs/aws-ebs-csi-driver#1537]
/kind bug

**What happened?**

I am trying to create a snapshot for EBS volume but snapshot is not getting created, also I am not seeing anything in the logs. 

**What you expected to happen?**

Snapshot should be created successfully

**How to reproduce it (as minimally and precisely as possible)?**

AWS EKS- 1.25

Installed using aws-ebs-csi-driver helm chart - (version: '2.17.2')

Values.yaml

```
controller:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  sdkDebugLog: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::************:role/***********
    create: true
    name: ebs-csi-controller-sa
sidecars:
  snapshotter:
    forceEnable: true
storageClasses:
- allowVolumeExpansion: true
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: ebs-sc
  parameters:
    encrypted: "true"
    kmsKeyId: arn:aws:kms:us-west-2:**********:key/***************
    type: gp3
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
```
Volume snapshot class created-

```
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: ebs.csi.aws.com
kind: VolumeSnapshotClass
metadata:
  creationTimestamp: "2023-03-14T20:39:46Z"
  generation: 1
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: csi-aws-vsc
  resourceVersion: "37885729"
  uid: 50a10f05-bfdf-4cea-b4c5-8a0e70c994c8
```
Status of volumesnapshot object-

```
 kubectl get volumesnapshot --all-namespaces
NAMESPACE   NAME                     READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT   CREATIONTIME   AGE
test        velero-ebs-claim-dl4fg                ebs-claim                                         csi-aws-vsc                                      77m
```

Logs of csi-snapshotter container

kubectl logs ebs-csi-controller-6c76d4c98b-m5sl5 -n kube-system -c csi-snapshotter
I0315 19:29:13.700242       1 main.go:104] Version: v6.2.1
I0315 19:29:13.798379       1 common.go:111] Probing CSI driver for readiness
I0315 19:29:13.799563       1 leaderelection.go:248] attempting to acquire leader lease kube-system/external-snapshotter-leader-ebs-csi-aws-com...
I0315 19:29:49.729902       1 leaderelection.go:258] successfully acquired lease kube-system/external-snapshotter-leader-ebs-csi-aws-com
I0315 19:29:49.730706       1 snapshot_controller_base.go:133] Starting CSI snapshotter

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.25
- Driver version: aws-ebs-csi-driver:v1.17.0

Please let me know in case any other information is required. Thanks in advance
