### ISSUE TITLE
Setting tag in VolumeSnapshotClass doesn't work as expected

### ISSUE THREAD

**Issue by hanyuel** [kubernetes-sigs/aws-ebs-csi-driver#1545]
/kind bug

**What happened?**
Create a snapshot using this VolumeSnapshotClass with the tag ``"Name=value1"``
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete
parameters:
  tagSpecification_1: "Name=value1"
````
In the AWS console, for the snapshot, the value for the "Name" tag is``<cluster-name>-dynamic-snapshot-<some-id>``which is automatically created.
**What you expected to happen?**
In the AWS console, for the snapshot, the value for the "Name" tag should be "value1". 

**How to reproduce it (as minimally and precisely as possible)?**
1. Follow this example in the repo to create a snapshot, but with the above VolumeSnapshotClass.
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot
2. Got to AWS console EC2, check the tags for the snapshot.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.24.10-eks-48e63af
```
- Driver version: v1.17.0
