### ISSUE TITLE
Snapshot tagging via VolumeSnapshotClass with string interpolation

### ISSUE THREAD

**Issue by hanyuel** [kubernetes-sigs/aws-ebs-csi-driver#1553]
**Is your feature request related to a problem? Please describe.**
Currently, EBS CSI Driver supports snapshot tagging via ``VolumeSnapshotClass.parameters``. If you declare ``VolumeSnapshotClass`` with ``parameters`` using ``tagSpecification`` prefix like this
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete
parameters:
  tagSpecification_1: "key1=value1"
```
The CSI Driver will add the key-value pair "key1=value1" as tag to the snapshot created using this VolumeSnapshotClass. 

This "static" tagging has its limitations. For example, all snapshots created using the same VolumeSnapshotClass will have the same tags (from VolumeSnapshotClass.parameters).
Users have also expressed interests in adding tags from the snapshot-level such as snapshot name&namespace to EBS snapshots.

**Describe the solution you'd like in detail**
The CSI ``external-snapshotter`` (when the --extra-create-metadata flag set) exposes these parameters, snapshot name, namespace and VolumeSnapshotContent name to the CSI Driver, in ``CreateSnapshotRequest``:
- csi.storage.k8s.io/volumesnapshot/name
- csi.storage.k8s.io/volumesnapshot/namespace
- csi.storage.k8s.io/volumesnapshotcontent/name

These parameters are dynamically generated at runtime. Reference: https://kubernetes-csi.github.io/docs/external-snapshotter.html#volumesnapshot-and-volumesnapshotcontent-parameters

We will implement the support in CSI Driver to allow these VolumeSnapshot and VolumeSnapshotContent parameters to be added to snapshot tags, with runtime string interpolation , in a similar way to [StorageClass tagging](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md).

Example 1
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete
parameters:
  tagSpecification_1: "key1={{ .VolumeSnapshotNamespace }}"
  tagSpecification_2: "key2={{ .VolumeSnapshotName }}"
  tagSpecification_3: "key3={{ .VolumeSnapshotContentName }}"
```
Create a snapshot with "default" namespace and "ebs-vs" name and from VolumeSnapshotContent name "ebs-vsc". The snapshot will have these tags
```
key1=default
key2=ebs-vs
key3=ebs-vsc
```
Example 2
More expressive tags w/ certain string interpolation functions:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Delete
parameters:
  tagSpecification_1: "key1={{ .VolumeSnapshotNamespace | contains "prod" }}"
  tagSpecification_2: "key2={{ .VolumeSnapshotNamespace | field "-" 2 | toUpper }}"
```
If the VolumeSnapshot namespace is "prod-na-test", the snapshot will have these 2 tags:
```
key1=true
key2=TEST
```
**Describe alternatives you've considered**
None.

**Additional context**
Related issue: #1261 #1453
