### ISSUE TITLE
Throughput parameter doesn't work

### ISSUE THREAD

**Issue by aiell0** [kubernetes-sigs/aws-ebs-csi-driver#1583]
/kind bug

**What happened?**
Throughput parameter on StorageClass not being implemented for dynamic provisioning.

**What you expected to happen?**
I was using a `gp3` EBS type and specified throughput as 250Mb/s, and it came up as 125Mb/s.

**How to reproduce it (as minimally and precisely as possible)?**
Define a StorageClass as follows:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: somename
parameters:
  encrypted: "true"
  iops: "5000"
  kmsKeyId: "kmskeyId"
  throughput: "250"
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
  
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.24.10-eks-48e63af
Kustomize Version: v4.5.4
Server Version: v1.25.8-eks-ec5523e
```
- Driver version: v1.18.0
