### ISSUE TITLE
volumemodifier container does not start

### ISSUE THREAD

**Issue by ethan-steinman-j1** [kubernetes-sigs/aws-ebs-csi-driver#1618]
/kind bug

**What happened?**
I'm migrating from the EKS addon version of the driver at 1.17.0 to a Helm managed version of the driver at 1.19.0.  I enabled the new volumemodifier feature, and that container never properly starts.
These are the logs output by the container:
```bash
kubectl logs -n kube-system ebs-csi-controller-6c4dc95577-fg4tb -c volumemodifier
exec /bin/volume-modifier-for-k8s: exec format error
```

**What you expected to happen?**
The volumemodifier container starts when enabled.

**How to reproduce it (as minimally and precisely as possible)?**
Chart version: 2.19.0
values.yaml:
```yaml
controller:
  volumeModificationFeature:
    enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${role_arn}
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.4-eks-0a21954", GitCommit:"4a3479673cb6d9b63f1c69a67b57de30a4d9b781", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:09Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 1.19.0
