### ISSUE TITLE
Tag volumes with namespace - support for custom Tag key

### ISSUE THREAD

**Issue by peteroruba** [kubernetes-sigs/aws-ebs-csi-driver#1664]
**Is your feature request related to a problem? Please describe.**
I would like to have all EBS Volumes tagged with a custom tag key ("namespace") with the value being the namespace the volume is being created for. Currently the namespace is being used in a tag value, but the tag key is "kubernetes.io/created-for/pvc/namespace". This we cannot use as Cost Allocation Tag, which is our final goal. 

**Describe the solution you'd like in detail**
We would like to be able to specify tags via pre defined variables like "${namespace}" so that those can be used in tag names or values. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ConnorJC3** [comment]
Hi @peteroruba - that is already possible via our tagging interpolation feature! See the documentation here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md#storageclass-tagging

For a concise example, this `StorageClass` would tag all volumes with the namespace under the key `VolumeNamespace`:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  tagSpecification_1: "VolumeNamespace={{ .PVCNamespace }}"
```

Alternatively, if you wish to apply this to all volumes, regardless of `StorageClass`, you can supply it via the `--extra-tags` CLI option (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/options.md), for example `--extra-tags="VolumeNamespace={{ .PVCNamespace }}"`.
