### ISSUE TITLE
Tags Not Working

### ISSUE THREAD

**Issue by rjop-hccgt** [kubernetes-sigs/aws-ebs-csi-driver#1672]
/kind bug

**What happened?**
I am trying to set tags on the StorageClass as specified in the documentation.

**What you expected to happen?**
Tags should be reflected in the volume.

**How to reproduce it (as minimally and precisely as possible)?**
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  tagSpecification_1: "key=value"
```

**Anything else we need to know?**:
I believe this is a bug in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/c4d628dae57c6ff8eb5fb6e6b97a78e1203ab26b/pkg/driver/constants.go#L90 since on the controller class, it is looking for lowercase keys: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/c4d628dae57c6ff8eb5fb6e6b97a78e1203ab26b/pkg/driver/controller.go#L144

Changing the constant name to lower case should fix this issue.

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.2-eks-c12679a", GitCommit:"002c6bc4e142b1f48b9405140e559194a094dcff", GitTreeState:"clean", BuildDate:"2023-05-22T20:23:13Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
- Driver version:
v1.20.0-eksbuild.1

**Comment by torredil** [comment]
@rjop-hccgt In the `default` case of this switch statement, the `strings.HasPrefix(key, TagKeyPrefix)` comparison uses the original `key` value from the input parameters, which is not converted to lowercase. Thus, `tagSpecification_1` is a valid key.

The specified StorageClass above is invalid:

```
error: error when retrieving current configuration of:
Resource: "storage.k8s.io/v1, Resource=storageclasses", GroupVersionKind: "storage.k8s.io/v1, Kind=StorageClass"
Name: "", Namespace: ""
from server for: "manifests/storageclass.yaml": resource name may not be empty
```


Here is a valid example:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: ebs-sc
parameters:
  tagSpecification_1: "key=value"
```
<img width="423" alt="Screenshot 2023-07-05 at 2 19 49 PM" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/99845161/227002bd-09f7-447f-9bce-16bf3dd55fa1">
