### ISSUE TITLE
Volumesnapshot not watched and never ready

### ISSUE THREAD

**Issue by Cedric-lefebvre-mgx** [kubernetes-sigs/aws-ebs-csi-driver#1729]
Hi, i'm currently experiencing an issue when trying to restore an existing aws ebs snapshot to a pvc storage.
I'm currently trying with a grafana ebs storage and i can always see that the VolumeSnapshot is not ready.

helm chart: aws-ebs-csi-driver
source: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
version: 2.22.0
container image: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v6.2.2-eks-1-27-9

**Here are my files:**

VolumeSnapshotClass:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ebs-csi-aws
driver: ebs.csi.aws.com
deletionPolicy: Delete
```

VolumeSnapshotContent (ready):
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: grafana-content
spec:
  deletionPolicy: Retain
  driver: ebs.csi.aws.com
  source:
    snapshotHandle: snap-xxxxxxxxxxxxxxxxx
  volumeSnapshotRef:
    name: grafana
    namespace: monitoring
```

VolumeSnapshot (not ready):
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: grafana
spec:
  source:
    volumeSnapshotContentName: grafana-content
  volumeSnapshotClassName: ebs-vsc
```

I don't know if it's normal but i don't see in the logs of the csi-snapshotter container any logs about watching the volumesnapshot, but i see it for the others:

```
reflector.go:221] Starting reflector *v1.VolumeSnapshotClass (15m0s) from k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169
reflector.go:221] Starting reflector *v1.VolumeSnapshotContent (15m0s) from k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169
reflector.go:257] Listing and watching *v1.VolumeSnapshotContent from k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169
reflector.go:257] Listing and watching *v1.VolumeSnapshotClass from k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169
util.go:188] storeObjectUpdate: adding content "grafana-content", version xxxxxx
util.go:216] storeObjectUpdate updating content "grafana-content" with version xxxxxx
main.go:184] CSI driver name: "ebs.csi.aws.com"
main.go:222] Start NewCSISnapshotSideCarController with snapshotter [ebs.csi.aws.com] kubeconfig [] csiTimeout [1m0s] csiAddress [/var/lib/csi/sockets/pluginproxy/csi.sock] resyncPeriod [15m0s] snapshotNamePrefix [snapshot]
```

I tried many different setup, even trying to create a snapshot from an existing PVC but no luck. Did anyone experience that and could give me some insight on my wrong configuration?
