### ISSUE TITLE
Add the ability to provide arbitrary EBS volume tags

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/aws-ebs-csi-driver#180]
**Is your feature request related to a problem? Please describe.**
With dynamically provisioned volumes there is always a danger of having orphaned EBS volumes. With current implementation, the only way to tie an EBS volume to a resource in Kubernetes is via the `CSIVolumeName` tag that gets automatically applied or with `volumeHandle` in the PV spec. However, both of these will not work if the Kubernetes resource is deleted and the EBS volume persists (either due the `ReclaimPolicy` or some bug where the volume is not deleted).

Providing a mechanism for operators to tag created volumes with custom tags, would help them in managing those EBS volumes, with this feature a user would be able to tag the volume with team, app, billing code, or whatever other tag they might already be using with other EBS volumes.

**Describe the solution you'd like in detail**
A new field can be added in the `StorageClass` `parameters` tag:
```
parameters:
  type: gp2 #gp2, io1, sc1, st1 - io1 requires 'iopsPerGB' to be set
  fsType: ext4 # ext4, ext3, ext2
  encrypted: "false"  # false/true
  additionalTags: "team=kubernetes,app=myapp,important"
```
The driver would perform a single validation:
* `additionalTags` does not contain `CSIVolumeName`, as that is reserved to be used by the driver.

Otherwise tags would be passed along to the AWS API request and if any of those validations fail, that error will be propagated back to the user via Kubernetes events.

**Describe alternatives you've considered**
Another option would be for the user to pass these tags in the PVC spec via an annotation. AFAIK this is not supported by the CSI spec.

**Additional context**
I might be wrong here but I believe the AWS cloud-provider supports this feature.

**Comment by frittentheke** [comment]
This feature also has some nice security implications.... I personally would like my provisioners IAM policy to require certain tags to be applied and then only allow the attacher to attach such volumes in their policy.

Otherwise I could i.e. hack into a worker node and reattach i.e. an etcd volume from another, totally unrelated EC2 (yeah, I know about encryption at rest for etcd 😉)

Just best practice on AWS: https://aws.amazon.com/de/premiumsupport/knowledge-center/iam-policy-tags-restrict/

**Comment by mgoodness** [comment]
A StorageClass parameter would not be sufficient for my use-case, which requires every EBS volume to be tagged with a product code for cost show-back purposes. We have hundreds of these codes. I'd rather not have to create the same number of StorageClasses (potentially multiplied by some combination of other parameters) for every cluster.

**Comment by dkoshkin** [comment]
There has been an ongoing discussion [here](https://github.com/kubernetes-csi/external-provisioner/issues/86). 
At this point it is not possible to get the PVC annotations as that would leak the Kubernetes implementation details in the CSI spec.

**Comment by leakingtapan** [comment]
The issue mentioned by @dkoshkin is currently the biggest issue blocking us from support this feature in PVC. [Here](https://github.com/kubernetes-csi/external-provisioner/issues/170) is another related discussion.

**Comment by jieyu** [comment]
OK, looks like upstream does not like the either of the proposals. But this is a real production issue. Can we do some workaround like: introduce a config options (i.e., a cmdline flag) for the controller service so that it'll always attach some tags to all the dynamically provisioned EBS volumes. The default can be empty so that it matches the current behavior. Thoughts?

**Comment by leakingtapan** [comment]
Given my understanding of the use cases, we need a way to dynamically tag the volumes given some user input. Passing the tag through controller service cmd flag won’t help in those cases

**Comment by leakingtapan** [comment]
I remember chatted with @saad-ali a while back. One potential solution to this problem could be user creates volume tags inside PV annotation, and we create a separated small controller that watches PV and it reads PV's annotation and tags the corresponding volume with the tags.

@mgoodness @frittentheke @jieyu @dkoshkin WDYT?

**Comment by dkoshkin** [comment]
The PVs are not created by a user PVCs are, I think it would be strange as a user to have add annotations because how would you do it, a controller :P?

**Comment by jieyu** [comment]
@leakingtapan this is our issue: we need to make sure all volumes dynamic provisioned are tagged with a cluster uuid so that we can safely delete the volume during cluster teardown. For that particular use case, we don't necessarily need to dynamically tag the volumes given some user input.

That's the reason I was suggesting the above solution, which sounds less intrusive and backwards compatible.

**Comment by leakingtapan** [comment]
@jieyu I see your point. Just created a separate issue to track your request since I feel we might be able to solve it under that specific situation with your suggestion as one option.

**Comment by leakingtapan** [comment]
> The PVs are not created by a user PVCs are, I think it would be strange as a user to have add annotations because how would you do it, a controller :P?

If we were to provide arbitrary EBS volume tagging functionality, I think we need to consider both dynamic provisioning and static provisioning case. If we want user to create tag annotations as part of PVC, this solves for dynamic provisioning. But I'm not sure how it will work for static provisioning. 

But I agree that asking user to add annotation in PV when dynamic provisioning is used is weird.

**Comment by leakingtapan** [comment]
I created a high level design using operator for this problem.

**Comment by flickerfly** [comment]
Is there two different problems here? I can't create an EBS volume without an OWNER tag due to billing requirements forcing me to configure other storage. That can be the same tag every time when associated with the cluster. Perhaps that's an easier problem to solve first? 

Then figuring out how to provide a method for changing up tags depending on certain scenarios can come as a follow-up problem?

**Comment by jieyu** [comment]
@flickerfly you might want to checkout this feature https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/333

**Comment by rverma-jm** [comment]
Hijacking this open issue, but wondering if we can propagate ASG tags to ebs, may be indirectly using the ec2 tags. that would be really helpful

**Comment by infa-ssaurabh** [comment]
```--extra-volume-tags``` works. But This way all the volumes will have same tags. Can't we provide any annotation etc in PVC manifest so that above argument takes the value dynamically instead of fixed?

**Comment by edgarcolque** [comment]
Hello,
   Is there any way to have the same tags  that we have with kubernetes.io/aws-ebs
Example:
kubernetes.io/created-for/pvc/name
kubernetes.io/created-for/pvc/namespace

or add dynamically a Tag to identify the Statefulset  owner, Is that possible with the latest version?

**Comment by bitva77** [comment]
AWS: "TAG EVERYTHING!"
Users:  "We'd like to add tags to our EBS volumes created by PV's"
AWS:  "Nah"

**Comment by mapdegree** [comment]
Any updates on the feature request from the AWS product group to add arbitrary AWS tags on EBS volumes via the CSI plugin?

Having AWS tags provisioned through a K8S manifest for an EBS volume is an essential functionality for us for various reasons (security, cost monitoring, etc.).

**Comment by wongma7** [comment]
What is missing, is the extraTags/extraVolumeTags argument sufficient? https://github.com/kubernetes-sigs/aws-ebs-csi-driver#tagging. If you specify it, tags get added to all volumes provisioned by the plugin.

I am thinking we also need an extraTags StorageClass parameter to add more granularity?

**Comment by flickerfly** [comment]
@wongma7 I don't think I'm seeing the documentation you think I'm seeing so it is hard to say if this brings a solution or not. Is there better docs about implementing what you are talking about?

**Comment by wongma7** [comment]
@flickerfly it's the last row in the table, look for the string "extraTags". By "argument" it means argument to the ebs-csi-driver binary, i.e. the spec.containers.args.

If you are using helm, you can set it using  .Values.extraVolumeTags https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L70.

(I think this is another reason that an extraTags StorageClass parameter would be beneficial. it would be easier to document and configure versus this binary flag. that said, the existing documentation for this flag could clearly use improvement.)

**Comment by flickerfly** [comment]
What does it look like in a manifest directly? I don't usually use helm. Also, I'm not seeing anything on the extraVolumeTags and how it differs.

**Comment by wongma7** [comment]
Here's mine I just tested, you must edit args of the `aws-ebs-csi-driver` container (as opposed to the sidecar containers like `csi-resize` or `livenessprobe`. It should be the first entry in the `spec.containers` array.
```
$ kubectl get deployment -n kube-system ebs-csi-controller -o yaml
<snip>
    spec:
      containers:
      - args:
        - controller
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --v=2
        - --extra-tags=wongma7=wongma7,key=value
<snip>
        image: 280347406217.dkr.ecr.us-west-2.amazonaws.com/aws-ebs-csi-driver:31300
<snip>
```

There is no functional difference between extraVolumeTags and extraTags, you can use either or, but extraVolumeTags is deprecated for some reason.

I created a new issue https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/930 to improve the documentation of extraTags, in fact I had to consult the code myself to see the difference between extraVolumeTags and extraTags which is not good.

This issue #180 will continue to track the need for an "extraTags" or "additionalTags" StorageClass parameter.

**Comment by flickerfly** [comment]
@wongma7 Thank you for that! I sub'd to #930. 

If what I'm understanding is correct, I'd not currently be able to have any tags unique to specific situations. When I can add these to the StorageClass, I'd need to have a different StorageClass in order to have a different set of tags for each namespace for example? Ideally, I'd like to set the tags at the PVC and have them passed down. This would matter in a scenario where I'm billing  different groups inside the same company using the same cluster so need to track storage usage on the AWS bill to pass on.

**Comment by bitva77** [comment]
Appreciate the `extraTags` option.

However, is there any way to add tags to an EBS volume based on the `PersistentVolume`?  I'd love to be able to see which service/pod an EBS volume was created by.

Setting `extraTags` in the driver helps with cluster identification but not specifically which pod created said volume

**Comment by pierluigilenoci** [comment]
@wongma7 having the PVC name and namespace would already be great, perhaps using the syntax used by EKS's default storage class. 

```yaml
kubernetes.io/created-for/pv/name:     
kubernetes.io/created-for/pvc/name:     
kubernetes.io/created-for/pvc/namespace:
```

**Comment by pierluigilenoci** [comment]
Even for EFS it would be nice to have it. Ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/446

**Comment by wongma7** [comment]
@pierluigilenoci I just found while trying to add it that this functionality already exists. To enable it you have to set extraCreateMetadata true in helm chart. After you do so, volumes created by the CSI provisioner will have thos same tags. kubernetes.io/created-for/pv/name:     
kubernetes.io/created-for/pvc/name:     
kubernetes.io/created-for/pvc/namespace:
I submitted a PR https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/937 to enable extraCreateMetadata by default, i don't see any reason to leave it disabled.

@bitva77 so if you set extraCreateMetadata true (pass extra-create-metadata flag to the external-provisioenr container) then the volume will have the tags containing PV name as described above. Populating more info like pod name is not technically feasilbe. this is because PVCs and PVs can be created asynchronously from the Pods consuming them and a given PVC might be used by multiple Pods over its lifetime. So the best you can do is, given the tag that says the PVC name, work backwards from PVC to figure out what Pod is using it. I know it's not ideal but I can't think of an alternative.

**Comment by pierluigilenoci** [comment]
Thank you @wongma7, I try it right away!

**Comment by danielwegener** [comment]
Works great, Thanks!

**Comment by hywook4** [comment]
> > When I can add these to the StorageClass, I'd need to have a different StorageClass in order to have a different set of tags for each namespace for example? Ideally, I'd like to set the tags at the PVC and have them passed down.
> 
> The only metadata about a PVC that the CSI driver has access to is its name and namespace, so it won't be possible to read a PVCs' annotations and pass them down to set tags accordingly (as was originally suggested in this issue), but it will be possible to use the namespace. So what we could do is A) add another boolean StorageClass parameter to control whether to add PVC name and namespace tags to provisioned volumes. Or B) have the hypothetical `extraTags` parameter respect a template string like {{namespace}} so that if I set `extraTags` to `namespace={{namespace}},key=value` the driver will tag volumes accordingly. Either way it would save you from having to create a StorageClass per-namespace. Without either A) or B), then yes you would have to create a StorageClass per namespace and then get creative with https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota to enforce that e.g. PVCs in namespace 1 cannot use StorageClass 2.
> 
> I don't think it's generally desirable to let the PVC creator dictate tags anyway, because using your billing example, you wouldn't want the PVC creator to tag the volume such that somebody else gets billed.

Hi @wongma7 
I'm trying to add dynamic extraVolumeTags using the metadata that CSI driver can access. 
I'm using helm to deploy the Daemonset. Could you help me how to use the metadata to add custom volume tag?
For example.
I'd like to add Name tag so 

`extraVolumeTags:
  Name: {{namespace}}-{{name}}`
And namespace and name would be the metadata that CSI driver can access. Could you give me guide for this?

Thank you.

**Comment by harshdevl** [comment]
@hywook4
i think i might have fix for you 

every time you make new volume you'll redeploy ebs-csi driver with extra-key tags suggested in README.md. this extra-key tag will be Name and value will be provided by config-map that will also be made directly.

i was using it with helm charts and i also had issue with naming EBS volumes in aws so i came with this solution.

Script that will deploy EBS-csi driver along with config-map and helm chart 

```
#!/bin/bash

if [[ -z "$1" ]]
    then
        echo -e "error: \033[31;7m Please Give name for Deployment.. example : EBS_name.sh <chartname> <path_for_chart>\e[0m";
    exit
fi

if [[ -z "$2" ]]
    then
        echo -e "error: \033[31;7m Please Give path for chart.. example : EBS_name.sh $1 <path_for_chart>\e[0m";
    exit
fi

kubectl delete -f controller.yaml -n kube-system
kubectl delete configmap name-config -n kube-system
kubectl create configmap name-config --from-literal=SPECIAL_NAME_KEY=$1 -n kube-system
kubectl apply -f controller.yaml -n kube-system
helm install $1 $2 -n $1 --create-namespace
```
for this i had controller.yaml file in the same location as this script
which i use to deploy ebs-csi driver with configmap to extract that value and use it to tag valume with Name Tag.

```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ebs-csi-controller
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebs-csi-controller
      app.kubernetes.io/name: aws-ebs-csi-driver
  template:
    metadata:
      labels:
        app: ebs-csi-controller
        app.kubernetes.io/name: aws-ebs-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: ebs-csi-controller-sa
      priorityClassName: system-cluster-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      containers:
        - name: ebs-plugin
          image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            # - {all,controller,node} # specify the driver mode
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --v=2
#######################change i made for extract value from configmap #############
            - --extra-tags=Name=$(SPECIAL_NAME_KEY)
 ##################################
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: CSI_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: key_id
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access_key
                  optional: true
#########################################change i made to use configmap for Tag value####################
            - name: SPECIAL_NAME_KEY
              valueFrom: 
                configMapKeyRef:
                  name: name-config
                  key: SPECIAL_NAME_KEY
###################################################
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
          args:
            - --csi-address=$(ADDRESS)
            - --v=2
            - --feature-gates=Topology=true
            - --extra-create-metadata
            - --leader-election=true
            - --default-fstype=ext4
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
          args:
            - --csi-address=$(ADDRESS)
            - --v=2
            - --leader-election=true
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election=true
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
          imagePullPolicy: Always
          args:
            - --csi-address=$(ADDRESS)
            - --v=2
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
          args:
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
```

And it works best.
