### ISSUE TITLE
Helm chart does not advertise special annotation needed if EKS IAM for SA is used

### ISSUE THREAD

**Issue by tporeba** [kubernetes-sigs/aws-ebs-csi-driver#1803]
When configuring `aws-ebs-csi-driver` with EKS IAM for serviceaccount I lost a lot of time because of missing annotation in my values.yaml:
```
controller:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:<partition>:iam::<account>:role/ebs-csi-role
node:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:<partition>:iam::<account>:role/ebs-csi-role
```

Only after trying out https://github.com/kubernetes-sigs/aws-efs-csi-driver I noticed that they have [documentation](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-create.md?plain=1#L93-L108) describing required annontations on service account. They even advertise it in their default values.yaml [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L89-L90) and [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L157-L158)

/feature

Why not do the same for `aws-ebs-csi-driver`? Let's add at least comments in default `values.yaml`, as people usually look there when using chart for the first time.

A dedicated documentation like https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-create.md wouldn't hurt too.
