### ISSUE TITLE
Add support for an ephemeral volume using EBS

### ISSUE THREAD

**Issue by akloss-cibo** [kubernetes-sigs/aws-ebs-csi-driver#1964]
**Is your feature request related to a problem? Please describe.**
As described [here](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#types-of-ephemeral-volumes), Kubernetes itself supports ephemeral volumes provided by a CSI driver.  The AWS EBS CSI driver does not appear to support this feature.  When configured to allow them (by changing the `CSIDriver` to include `Ephemeral` in the `volumeLifecycleModes`, pods cannot start configured with an ephemeral volume:
```
  Warning  FailedMount  3s (x10 over 4m13s)  kubelet            MountVolume.SetUp failed for volume "home" : rpc error: code = InvalidArgument desc = Staging target not provided
```

While it is possible I don't have the `volumeAttributes` configured correctly, after reviewing the source code, I believe this feature is not implemented.

**Describe the solution you'd like in detail**
Attempting to provision an ephemeral EBS volume works, and the volume is deleted when the pod exits.

**Describe alternatives you've considered**
We currently use steps in an Argo Workflow to provision and de-provision EBS volumes using PersistentVolumeClaims.  This creates a lot of boilerplate and the opportunity for EBS volumes to leak if Argo Workflows doesn't execute the step that deletes the PersistentVolumeClaim.

**Additional context**

I've considered https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/482 and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1527 which, as I understand them, are both about utilizing the directly attached SSD storage that is available on some EC2 instances.  This request is about utilizing the ephemeral volume feature in Kubernetes backed by EBS volumes.  This would allow us to provision very large ephemeral storage without resorting to managing relatively short-lived PersistentVolumeClaims.

**Comment by AndrewSirenko** [comment]
Hi @akloss-cibo, 

Thank you for your request, it is reasonable. Our team will look into it. 

/priority backlog
/feature

**Comment by emeraldsanto** [comment]
I'm using the `aws-ebs-csi-driver` (version `1.18.0`) add-on along with Karpenter (version `0.29.2`) on an EKS cluster (version `1.26.0`) and ephemeral volumes have been working as expected. 

This is my `StorageClass` definition

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: runner-ephemeral-storage
parameters:
  type: gp3
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

and this is the volume claim I add to my templates

```yaml
volumes:
- ephemeral:
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 132Gi
        storageClassName: runner-ephemeral-storage
  name: shared
```

Now, there are [some differences](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) between CSI ephemeral volumes and generic ephemeral volumes but I thought I would share my configuration in case it helps!
