### ISSUE TITLE
node on persistent volume claim is not true representation of what is as per aws 

### ISSUE THREAD

**Issue by govinda-attal** [kubernetes-sigs/aws-ebs-csi-driver#2033]
/kind bug

**What happened?**
Context: stateful set with persistent volumes and claims are created as per inline template within the spec (ReadWriteOnce access mode)
`volume.kubernetes.io/selected-node` annotation on pvc was different to one that was reported on aws console

Extract of template within stateful set
```yaml
volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: zk-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: gp2
      volumeMode: Filesystem
    status:
      phase: Pending
```

The way we noticed this that there was a mismatch of node-names on pvc and pod (to which pvc was bound). Which led us to validate against AWS Console and here we noticed that annotation on pvc was different to what actual reality was. 

```bash
❯ k get pvc -n dpm -l layer=kafka-zk --output=custom-columns="Name:.metadata.name,Node:.metadata.annotations.volume\.kubernetes\.io\/selected-node,Status:.status.phase"
Name                                  Node                                           Status
zk-data-volume-dpm-kafka-job-zk-0     ip-192-168-1-71.us-east-2.compute.internal     Bound
zk-data-volume-dpm-kafka-job-zk-1     ip-192-168-40-81.us-east-2.compute.internal    Bound
zk-data-volume-dpm-kafka-job-zk-2     ip-192-168-76-224.us-east-2.compute.internal   Bound
....

❯ k get po -n dpm -l layer=kafka-zk -o=custom-columns="Name:.metadata.name,Node:.spec.nodeName,Status:.status.phase"
Name                   Node                                           Status
dpm-kafka-job-zk-0     ip-192-168-1-71.us-east-2.compute.internal     Running
dpm-kafka-job-zk-1     ip-192-168-42-213.us-east-2.compute.internal   Running
dpm-kafka-job-zk-2     ip-192-168-65-87.us-east-2.compute.internal    Running
...

```
However the node-name of volume as per aws console matched with the node-name of the pod to which it was bound.

**What you expected to happen?**
pvc annotation `selected-node` should have correctly identified node name

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**: N/A

**Environment**
- Kubernetes version (use `kubectl version`): Server version - v1.27.11-eks-b9c9ed7
- Driver version: v1.23.0-eksbuild.1

<img width="1407" alt="Volume-Attached-To-Instance-On-AWS-Console" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/30035879/beafa100-fd4b-43a4-80d7-3f58d0d169f6">
