### ISSUE TITLE
Driver volume type selection inconsistency

### ISSUE THREAD

**Issue by maximveksler** [kubernetes-sigs/aws-ebs-csi-driver#2092]
/kind bug

**What happened?**
Using StorageClass with `parameters.type: gp3` coupled with annotation `ebs.csi.aws.com/volumeType: io2` produces varying results based on existance of `ebs.csi.aws.com/throughput` annotation.

**What you expected to happen?**

Volume should always be created with type `io2` or the ability to specify volume type should be consistent using an annotation.

**How to reproduce it (as minimally and precisely as possible)?**
This produces Volume of type `io2`

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1
  namespace: default
  annotations:
    ebs.csi.aws.com/iops: '9005'
    ebs.csi.aws.com/volumeType: io2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 505Gi
  storageClassName: ebs
  volumeMode: Filesystem

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

This produces volume of type `gp3`

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1
  namespace: default
  annotations:
    ebs.csi.aws.com/iops: '9005'
    ebs.csi.aws.com/volumeType: io2
    ebs.csi.aws.com/throughput: "805"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 505Gi
  storageClassName: ebs
  volumeMode: Filesystem

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
❯ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0
```
- Driver version:
```
602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-ebs-csi-driver:v1.32.0
```

**Comment by maximveksler** [comment]
possible workaround is setting throughput to str "0", i.e.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1
  namespace: default
  annotations:
    ebs.csi.aws.com/iops: '9005'
    ebs.csi.aws.com/volumeType: io2
    ebs.csi.aws.com/throughput: '0'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 505Gi
  storageClassName: ebs
  volumeMode: Filesystem
```
