### ISSUE TITLE
Multi-Attach io2 - can't mount device with `Invalid argument` error

### ISSUE THREAD

**Issue by obeyda** [kubernetes-sigs/aws-ebs-csi-driver#2173]
I am trying to mount an io2 volume using static provisioning: 

pv.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-aws-pv
spec:
  capacity:
    storage: 3Ti
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-xxxxxxxxx
    fsType: ext4
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-east-2a

```

pvc.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-aws-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  volumeName: data-aws-pv
  volumeMode: Block
```

pod.yaml
```yaml
<...>
spec:
  initContainers:
    - command:
        - sh
        - '-c'
        - |
          mkdir -p /app/data
          mount /dev/xvdf /app/data
          echo $(whoami)
          # check files
          echo "Listing files in /app/data ..."
          ls -al /app/data
      image: alpine
      name: mount-block-device
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
      volumeDevices:
        - devicePath: /dev/xvdf
          name: data-volume
      volumeMounts:
        - mountPath: /app/data
          name: data-mount


  containers:
    - image: alpine
      imagePullPolicy: IfNotPresent
      name: app
      securityContext: {}
      volumeMounts:
        - mountPath: /app/data
          name: data-mount


  restartPolicy: Never
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-aws-pvc
    - emptyDir: {}
      name: data-mount
```

- I have the io2 volume created and already populated with data.
- Multi-Attach is enabled in us-east-2a

The init container's output says that the mount command is failing with 

```bash
mount: mounting /dev/xvdf on /app/data failed: Invalid argument
```

checking with dmesg shows this: 
```
[ 1063.545150] zonefs (nvme2n1) ERROR: Not a zoned block device
```

My volume: 
![Capture-2024-10-08-154035-](https://github.com/user-attachments/assets/08b47e0e-de78-42c6-84a9-f2995b15195b)

k8s version: `1.30`
aws-ebs-csi-driver: `v1.32.0-eksbuild.1` (advanced config only have default storage class enabled)
