### ISSUE TITLE
Support for ReadOnlyMany does not work

### ISSUE THREAD

**Issue by da-amit-mujawar** [kubernetes-sigs/aws-ebs-csi-driver#2178]
/kind bug

**What happened?**
When we try to use ReadOnlyMany, the volume attachment fails with error 
`1 controller.go:637] "isValidCapability: access mode is not supported" accessMode="MULTI_NODE_READER_ONLY"`

**What you expected to happen?**
Should have worked and mounted the volume in the Pod. 
Question: Which modes are supported by this driver? I cannot find a documentation as to which modes are supported and which are not.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by ConnorJC3** [comment]
Hi, `ReadOnlyMany` support is not available in the EBS CSI Driver. This is because the only multi-node volume supported by the EBS CSI Driver is `ReadWriteMany` on block devices for [EBS Multi-Attach volumes](https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volumes-multi.html) (useful for some niche usecases such as clustered filesystems and software with specific support. EBS is unable to mount a block device read only, so we cannot support `ReadOnlyMany` block devices.

I will leave this issue open as a documentation issue for us to better document these limitations.

/retitle Better document supported access modes

**Comment by voliveira-tmx** [comment]
@ConnorJC3 

I'm getting the following error:

```
I0908 16:44:48.918641       1 controller.go:679] "isValidCapability: access mode is only supported for block devices" accessMode="MULTI_NODE_MULTI_WRITER"
E0908 16:44:48.918665       1 driver.go:113] "GRPC error" err="rpc error: code = InvalidArgument desc = Volume capabilities not supported"
```

But I did configure my StorageClass to provision `io2` type of EBS, which does support Multi-Attach. Is there anything I'm missing ?

This is how I configured the storage class on the values file:

```
aws-ebs-csi-driver:
  storageClasses:
    - name: ebs-sc
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      volumeBindingMode: Immediate
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        type: io2
        iops: "4000"
        encrypted: "true"
        csi.storage.k8s.io/fstype: ext4
```
Versions:
- Helm Chart = `v2.48.0`
- App Version = `v1.48.0`

Thank you!
