### ISSUE TITLE
Add tpl to serviceAccount annotations

### ISSUE THREAD

**Issue by denzhel** [kubernetes-sigs/aws-ebs-csi-driver#2241]
**Is your feature request related to a problem?/Why is this needed**
As we moved to handling all of our helm carts to Argo ApplicationSet we'd like the ability to have our annotations templated and dynamically set instead of hard coding each value for each environment

/feature

**Describe the solution you'd like in detail**
Have this line https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/a25f651b6f2e39ba1ef79dbac4d638f36ad62292/charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml#L11 changed to:
```
 {{- tpl (toYaml .) $ | nindent 4 }}
```
This will allow us to use the following:
```
controller:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.global.accountId }}:role/{{ .Values.global.env }}-ebs-csi-controller"
```
**Describe alternatives you've considered**
Repeat the code and hard code the IAM role above in each value file that represents each production evnironment
