### ISSUE TITLE
VolumeAttributesClass don't work

### ISSUE THREAD

**Issue by ihor-kokhan-onereach** [kubernetes-sigs/aws-ebs-csi-driver#2297]
/kind bug

**What happened?**
I try to add tags to volumes. But its not work for me.
I create VAC 
```
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: gp3
  namespace: kube-system
driverName: ebs.csi.aws.com
parameters:
  tagSpecification_1: "test=test"
```
and add to PVC spec `volumeAttributesClassName: gp3` config:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loki-read-0
  namespace: monitoring
  labels:
    app.kubernetes.io/component: read
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    k8slens-edit-resource-version: v1
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  finalizers:
    - kubernetes.io/pvc-protection
  selfLink: /api/v1/namespaces/monitoring/persistentvolumeclaims/data-loki-read-0
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-ed1af8d7-e4ca-45f0-a002-5ad553738395
  storageClassName: gp3
  volumeMode: Filesystem
  volumeAttributesClassName: gp3
```
But I still don't see `test=test `tag in AWS EC2 volumes.

**Environment**
- EKS 1.31 version
- Amazon EBS CSI Driver v1.38.1-eksbuild.1:
