### ISSUE TITLE
[chart] 2.39.2 - Add global property to allow subcharting

### ISSUE THREAD

**Issue by aballman** [kubernetes-sigs/aws-ebs-csi-driver#2319]
/kind bug

**What happened?**
A `values.schema.json` file was added

**What you expected to happen?**
That it would continue to allow me to use this chart as a subchart.

**How to reproduce it (as minimally and precisely as possible)?**
Use it as a subchart
```
apiVersion: v2
description: aws-ebs-csi-driver
name: chart-aws-ebs-csi-driver
version: 2.39.2
type: application
dependencies:
  - name: aws-ebs-csi-driver
    version: 2.39.2
    repository: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/
```
The below error is emitted when templating:
`- (root): Additional property global is not allowed`

**Anything else we need to know?**:
`values.schema.json` needs this property
```
"global": {
  "description": "Global values shared across all (sub)charts"
},
```

**Environment**
- Kubernetes version (use `kubectl version`): N/A
- Driver version: N/A
