### ISSUE TITLE
Cannot attach multiple instances to an io1 multi-attach volume

### ISSUE THREAD

**Issue by jicowan** [kubernetes-sigs/aws-ebs-csi-driver#2336]
/kind bug

**What happened?**
Tried to create an io1 multi-attach volume in us-west-2. The first pod attaches to the volume, but when the next pod tries to connect it throws an error saying, "Multi-Attach error for volume "pvc-f40d488f-275c-40a7-941c-03b6e5ab25eb" Volume is already used by pod(s) multi-attach-io1-c9467f94d-dkldq". Both pods are running on m4 instances in the same AZ. 

I know io2 only supports block mode. The documentation is a little unclear what io1 supports. 

**What you expected to happen?**
Both pods should be able to attach to the volume. 

**How to reproduce it (as minimally and precisely as possible)?**
StorageClass
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io1-sc
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  csi.storage.k8s.io/fstype: xfs
  iops: '1000'
  type: io1
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

PersistentVolumeClaim
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io1-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: io1-sc
  volumeMode: Filesystem
```

Deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-attach-io1
  namespace: default
  labels:
    name: multi-attach-io1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: multi-attach-io1
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: multi-attach-io1
    spec:
      nodeSelector: 
        eks.amazonaws.com/instance-category: m
        eks.amazonaws.com/instance-generation: 4
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: io1-claim
      containers:
        - name: busybox
          image: busybox
          command:
            - /bin/sh
            - '-c'
          args:
            - tail -f /dev/null
          resources: {}
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - multi-attach-io1
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.30
- Driver version: controlled by EKS auto mode
