### ISSUE TITLE
ModifyVolume via VolumeAttributesClass forces ebs-csi-controller into CrashLoopback when modifying PVC from gp2 to gp3

### ISSUE THREAD

**Issue by gpapakyriakopoulos** [kubernetes-sigs/aws-ebs-csi-driver#2340]
/kind bug

As the title suggests we are trying to modify an existing PVC from gp2 to gp3 EBS volume in our EKS cluster (version 1.31) using the VolumeAttributeClass approach of ModifyVolume.

We have created the following VolumeAttributeClass : 

```
---
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: gp3-update-class
driverName: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "128"
  encrypted: "true"
```

Our existing PVC looks as follows :

```
Name:          elasticsearch-data-es-es-ingest-2
Namespace:     siem
StorageClass:  gp2
Status:        Bound
Volume:        pvc-5aebc4f6-2194-4733-ae1c-47b493d2d63d
Labels:        common.k8s.elastic.co/type=elasticsearch
               elasticsearch.k8s.elastic.co/cluster-name=es
               elasticsearch.k8s.elastic.co/statefulset-name=es-es-ingest
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-10-0-16-75.eu-central-1.compute.internal
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      400Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       es-es-ingest-2
Events:        <none>
```

We apply the created VolumeAttributesClass via :

`kubectl patch pvc elasticsearch-data-es-es-ingest-2 --patch '{"spec": {"volumeAttributesClassName": "gp3-update-class"}}'`

Application is successful as seen here : 

```
NAME                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
elasticsearch-data-es-es-ingest-2   Bound    pvc-5aebc4f6-2194-4733-ae1c-47b493d2d63d   400Gi      RWO            gp2            gp3-update-class        57d
```

Immediately after applying the VolumeAttributesClass to the PVC, the csi-resizer container of the ebs-csi-controller (v. 1.39.0)  throws the following panic :

```
I0213 16:47:41.887270       1 controller.go:220] "Starting external resizer for modify volume" controller="ebs.csi.aws.com"
I0213 16:47:41.887332       1 controller.go:272] "Starting external resizer" controller="ebs.csi.aws.com"
I0213 16:47:41.887335       1 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0213 16:47:41.887362       1 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0213 16:47:42.080065       1 reflector.go:368] Caches populated for *v1beta1.VolumeAttributesClass from k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243
I0213 16:47:42.080506       1 reflector.go:368] Caches populated for *v1.PersistentVolumeClaim from k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243
I0213 16:47:42.081169       1 reflector.go:368] Caches populated for *v1.PersistentVolume from k8s.io/client-go@v0.31.0/tools/cache/reflector.go:243
E0213 16:47:42.088070       1 panic.go:261] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
	goroutine 324 [running]:
	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1dab898, 0x2ede620}, {0x1789ee0, 0x2e3f490})
		k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:107 +0x98
	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x1dab898, 0x2ede620}, {0x1789ee0, 0x2e3f490}, {0x2ede620, 0x0, 0x40006b3ab8?})
		k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:82 +0x60
	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4000702e00?})
		k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:59 +0x114
	panic({0x1789ee0?, 0x2e3f490?})
		runtime/panic.go:770 +0x124
	github.com/kubernetes-csi/external-resizer/pkg/modifycontroller.(*modifyController).syncPVC(0x400051a780, {0x4000498c30, 0x26})
		github.com/kubernetes-csi/external-resizer/pkg/modifycontroller/controller.go:281 +0x338
	github.com/kubernetes-csi/external-resizer/pkg/modifycontroller.(*modifyController).sync(0x400051a780)
		github.com/kubernetes-csi/external-resizer/pkg/modifycontroller/controller.go:243 +0xb4
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40006b3f28?)
		k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:226 +0x40
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000415a90, {0x1d88460, 0x4000475800}, 0x1, 0x40001159e0)
		k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:227 +0x90
	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000415a90, 0x0, 0x0, 0x1, 0x40001159e0)
		k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:204 +0x80
	k8s.io/apimachinery/pkg/util/wait.Until(...)
		k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:161
	created by github.com/kubernetes-csi/external-resizer/pkg/modifycontroller.(*modifyController).Run in goroutine 32
		github.com/kubernetes-csi/external-resizer/pkg/modifycontroller/controller.go:229 +0x1e0
 >
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x15190d8]

goroutine 324 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x1dab898, 0x2ede620}, {0x1789ee0, 0x2e3f490}, {0x2ede620, 0x0, 0x40006b3ab8?})
	k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:89 +0xf4
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4000702e00?})
	k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:59 +0x114
panic({0x1789ee0?, 0x2e3f490?})
	runtime/panic.go:770 +0x124
github.com/kubernetes-csi/external-resizer/pkg/modifycontroller.(*modifyController).syncPVC(0x400051a780, {0x4000498c30, 0x26})
	github.com/kubernetes-csi/external-resizer/pkg/modifycontroller/controller.go:281 +0x338
github.com/kubernetes-csi/external-resizer/pkg/modifycontroller.(*modifyController).sync(0x400051a780)
	github.com/kubernetes-csi/external-resizer/pkg/modifycontroller/controller.go:243 +0xb4
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40006b3f28?)
	k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000415a90, {0x1d88460, 0x4000475800}, 0x1, 0x40001159e0)
	k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000415a90, 0x0, 0x0, 0x1, 0x40001159e0)
	k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
	k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:161
created by github.com/kubernetes-csi/external-resizer/pkg/modifycontroller.(*modifyController).Run in goroutine 32
	github.com/kubernetes-csi/external-resizer/pkg/modifycontroller/controller.go:229 +0x1e0
```

The csi-resizer container runs with the following parameters : 

```
csi-resizer:
    Image:           602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/csi-resizer:v1.12.0-eks-1-31-11
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Args:
      --timeout=60s
      --csi-address=$(ADDRESS)
      --v=2
      --handle-volume-inuse-error=false
      --leader-election=true
      --kube-api-qps=20
      --kube-api-burst=100
      --workers=100
      --retry-interval-max=30m
      --feature-gates=VolumeAttributesClass=true
```

**Comment by AndrewSirenko** [comment]
Hi @gpapakyriakopoulos, thank you for your issue! 

One possible root cause is that `encrypted` is NOT a valid VAC parameter. Please remove that line from your VAC and try again?

Our list of valid modification parameters are listed in our [modify-volume documentation](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-1.39/docs/modify-volume.md#parameters). This includes `type`, `iops`, `throughput`, and tag modification.

We can do a better job distinguishing valid storageClass vs VolumeAttributesClass parameters by adding a section to our [parameters.md](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md), instead of having this list in this modify-volume documentation. I'll take an action item for that. 

---

As for why the nil pointer panic, that seems to be a bug with the upstream resizer sidecar itself: https://github.com/kubernetes-csi/external-resizer. However, I cannot reproduce this panic with either v1.12.0 or v1.13.1 of the resizer sidecar. 

These are the steps I was using to try to reproduce the issue:

```
kubectl apply -f - <<EOF
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: gp3-class
driverName: ebs.csi.aws.com
parameters:
  type: gp3
  throughput: "128"
  iops: "3000"
  encrypted: "true"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) | tee /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim1
EOF

```

`kubectl patch pvc ebs-claim1 --patch '{"spec": {"volumeAttributesClassName": "gp3-class"}}'

The resizer sidecar does not throw nil pointer error, it just has following logs:

```
I0213 18:54:41.543961       1 reflector.go:368] Caches populated for *v1.PersistentVolumeClaim from k8s.io/client-go@v0.31.0/tools/cache/refl
I0213 18:54:41.544359       1 reflector.go:368] Caches populated for *v1.PersistentVolume from k8s.io/client-go@v0.31.0/tools/cache/reflector
I0213 18:55:38.089221       1 event.go:389] "Event occurred" object="default/ebs-claim1" fieldPath="" kind="PersistentVolumeClaim" apiVersion
E0213 18:55:39.137904       1 controller.go:245] "Error syncing PVC" err="mark PVC \"ebs-claim1\" as modify volume failed, errored with: can'
I0213 18:55:41.149406       1 event.go:389] "Event occurred" object="default/ebs-claim1" fieldPath="" kind="PersistentVolumeClaim" apiVersion
E0213 18:55:41.165898       1 controller.go:245] "Error syncing PVC" err="mark PVC \"ebs-claim1\" as modify volume failed, errored with: can'
...
```

**Comment by gpapakyriakopoulos** [comment]
@AndrewSirenko Thanks for the amazingly fast response!

I'll test your suggestion and get back to you as soon as possible. In the meantime, for your reproduction scenario, maybe it has to do with the fact that the original `storageclass` I am migrating from is the EKS in-tree SC ? :

```
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  2y8d
```

**Comment by AndrewSirenko** [comment]
Yes I am able to now reproduce your issue... Looks like one cannot use VAC is PVC's SC's provisioner was an in-tree driver... 

I will raise an issue on the external-resizer project, and bring this up in the next SIG Storage implementation meeting on Monday. 

In the meantime, let me try to provide you a workaround to unblock your use case (swapping your PVC to no longer refer to the in-tree SC).  

For posterity, these are my reproduction steps for running into your issue:

```
kubectl apply -f - <<EOF
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: gp3-class
driverName: ebs.csi.aws.com
parameters:
  type: gp3
  throughput: "128"
  iops: "3000"
  encrypted: "true"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) | tee /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim1
EOF
```

```
`kubectl patch pvc ebs-claim1 --patch '{"spec": {"volumeAttributesClassName": "gp3-class"}}'
```

**Comment by AndrewSirenko** [comment]
Yep exactly. The PV resource of a migrated volume does not PV.Spec.CSI (it has PV.spec.awsElasticBlockStore instead).

We can trivially fix the nil pointer exception (by adding an extra nil check), but we still have to figure out what we should do in the migrated volume case. 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/migrated-to: ebs.csi.aws.com
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
...
spec:
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-045ec457863e5980b
...

```
