### ISSUE TITLE
[Deprecation Announcement] `volume-modifier-for-k8s`

### ISSUE THREAD

**Issue by torredil** [kubernetes-sigs/aws-ebs-csi-driver#2435]
## Summary

Effective immediately, the [volume-modifier-for-k8s](https://github.com/awslabs/volume-modifier-for-k8s) project (which enables EBS volume modifications in Kubernetes via annotations) is deprecated in favor of the native Kubernetes [VolumeAttributesClass](https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/) API.

No new features will be added to `volume-modifier-for-k8s`. Security and bug fixes will still be released until at least 6 months after Kubernetes `v1.34` is GA (*approximately Q1 2026, exact date is subject to change*).

## Background

The `volume-modifier-for-k8s` project was originally created to provide a solution for modifying EBS volume parameters in Kubernetes before a native solution existed. With the introduction of the `VolumeAttributesClass` API in Kubernetes, users now have a native, standardized way to manage these modifications.

See the original AWS storage blog describing the custom annotation volume modification approach for more context: [Simplifying Amazon EBS volume migration and modification on Kubernetes using the EBS CSI Driver](https://aws.amazon.com/blogs/storage/simplifying-amazon-ebs-volume-migration-and-modification-on-kubernetes-using-the-ebs-csi-driver/).

## Compatibility and Support

* AWS EBS CSI Driver versions `v1.35.0` and later fully support modifying volumes using `VolumeAttributesClass` for all properties previously supported via `volume-modifier-for-k8s`.
* `VolumeAttributesClass` support is available in Kubernetes `v1.31+` and is enabled by default on Amazon EKS clusters running this version.
* Users on older Kubernetes versions may continue using `volume-modifier-for-k8s`.

## Migration Guidance

We strongly encourage all users of `volume-modifier-for-k8s` to begin transitioning to the official Kubernetes solution. Here's a simple migration example:

Before (using `volume-modifier-for-k8s`):

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  annotations:
    ebs.csi.aws.com/volumeType: "gp3"
    ebs.csi.aws.com/iops: "4000"
```

After (using VolumeAttributesClass):

```
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: example-vac
driverName: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "4000"
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  volumeAttributesClassName: example-vac
```

## Additional Resources

* [Kubernetes Documentation on VolumeAttributesClasses](https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/)
* [AWS Blog Post on Using VolumeAttributesClasses with EKS](https://aws.amazon.com/blogs/containers/modify-amazon-ebs-volumes-on-kubernetes-with-volume-attributes-classes/)
* [EBS CSI Driver Documentation for Volume Modification](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/modify-volume.md)

## Support

Please reach out directly on this issue if you have questions or require assistance during this transition.

**Comment by ahilsend** [comment]
I've tried out the VolumeAttributesClass, but unfortunately can't get it it to work.

`VolumeAttributesClass`:
```
apiVersion: storage.k8s.io/v1beta1
driverName: ebs.csi.aws.com
kind: VolumeAttributesClass
metadata:
  name: vac-test
parameters:
  iops: "3100"
```

`PersistentVolumeClaim`:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-test-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: xfs-storage-class
  volumeAttributesClassName: vac-test
  volumeMode: Filesystem
  volumeName: pvc-fc8ab0dd-cd71-42e0-ad36-18019fc545c0
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
```

* EKS version: v1.32.2-eks-bc803b4
* aws-ebs-csi-driver addon: v1.41.0-eksbuild.1

I tried uninstalling, and re-installing the EBS CSI driver, but no success. There are no events on the PVC, like the driver doesn't do anything.
