### ISSUE TITLE
VAC tags should appear on volumes created with VAC

### ISSUE THREAD

**Issue by AndrewSirenko** [kubernetes-sigs/aws-ebs-csi-driver#2442]
**Is your feature request related to a problem? Please describe.**

Today, tags specified by a VolumeAttributesClass will only appear on EBS Volume associated with PVC if the VAC was added to PVC *after* volume creation [as shown in our example](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/modify-volume)

A PVC that was created with a specified volumeAttributesClassName should have the tags that the VAC specifies (this is what happens with other parameters like volume type)

**Describe alternatives you've considered**

Customers can specify tags in their storage class or the `--extra-tags` driver parameter. 

**Additional context**

The following manifests when created should yield an EBS Volume with location and cost-center tags. With EBS CSI Driver v1.41.0 it creates an io2 volume with no additional tags. 

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  volumeAttributesClassName: io2-class
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: public.ecr.aws/amazonlinux/amazonlinux
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) | tee /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
---
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: io2-class
driverName: ebs.csi.aws.com
parameters:
  type: io2
  iops: "3000"
  tagSpecification_1: "location=Seattle"
  tagSpecification_2: "cost-center="

```
