### ISSUE TITLE
restored snapshot volume contents are missing

### ISSUE THREAD

**Issue by paulmin55** [kubernetes-sigs/aws-ebs-csi-driver#426]
/kind bug

**What happened?**
I created an EBS volume snapshot attached to a statefulset pod using the ebs-csi-driver `VolumeSnapshot`.  The snapshot was created and the `Ready to Use` state was showing value: `true`.

Snapshot Status:
```
 $ kubectl describe volumesnapshot.snapshot.storage.k8s.io mysql-ebs-volume-snapshot
Name:         mysql-ebs-volume-snapshot
<shortened>
  Creation Time:  2019-12-08T02:22:05Z
  Ready To Use:   true
  Restore Size:   2Ti
```

When I restored the snapshot to mount point `/var/lib/mysql`, I noticed that the contents of the target volume mount on the container didn't contain the snapshot contents.

As a test, I restored the ebs-csi-driver created ebs snapshot through AWS console.  Then attached it to an ec2 instance outside of k8s cluster and confirmed the contents I expected from the snapshot existed in the target mount point.

**What you expected to happen?**
I expected the volume mount on a newly deployed pod referencing the ebs-csi-driver created snapshot to contain the original snapshotted data in `/var/lib/mysql` on snapshot restore.

**How to reproduce it (as minimally and precisely as possible)?**
1. Deploy Statefulset with volumeClaimTemplates referencing the ebs-csi-driver related StorageClass.
2. Create snapshot using VolumeSnapshot
3. Delete the Statefulset and PVC.
4. Redeploy the Statefulset with VolumeClaimTemplates.Datasource set to volume snapshot name on step 2 to restore the snapshot.
5. Target volume mount point is missing snapshotted data.

The following are the relevant spec snippets I'm using to reproduce causing the issue:

* This is the `VolumeSnapshot` spec:
```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mysql-ebs-volume-snapshot
spec:
  snapshotClassName: csi-aws-vsc
  source:
    name: mysql-ebs-claim-mysql-0
    kind: PersistentVolumeClaim
```

* This is the `StorageClass` spec:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc-encrypted
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
```

* This is my StatefulSet with relevant volume configs:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
<shortened>
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
<shortened>
       volumeMounts:
        - name: mysql-ebs-snapshot-claim
          mountPath: "/var/lib/mysql"
  volumeClaimTemplates:
  - metadata:
      name: mysql-ebs-snapshot-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc-encrypted
      resources:
        requests:
          storage: 3072Gi 
      dataSource:
        name: mysql-ebs-volume-snapshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
```

* CSIDriver spec:
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
spec:
  attachRequired: true
  podInfoOnMount: false
```

**Anything else we need to know?**:

* The original PV and PVC was provisioned using provisioner `ebs.csi.aws.com`.
* The storage request is greater than the snapshot restore size.
* I tried to restore the snapshot on a different mount point rather than /var/lib/mysql at it was still empty.
* A similar exercise worked on the same cluster with the snapshot example found [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot).

**Environment**
- Kubernetes version (use `kubectl version`):
  EKS 1.14 platform eks.2

- Driver version:
* ebs-plugin: amazon/aws-ebs-csi-driver:v0.4.0
* csi-provisioner: quay.io/k8scsi/csi-provisioner:v1.3.0
* csi-attacher: quay.io/k8scsi/csi-attacher:v1.2.0
* csi-snapshotter: quay.io/k8scsi/csi-snapshotter:v1.1.0
* csi-node-driver-registrar: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
