### ISSUE TITLE
Adding tags semi-dynamically

### ISSUE THREAD

**Issue by mrPsycho** [kubernetes-sigs/aws-ebs-csi-driver#436]
Hello, 

this change https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/333 is very helpful.
but, is it possible to put tags from enviroment variables? 

i mean next:
on latest version of driver `CSIVolumeName` tag is added with value from `Volume` field. But, is it possible to add other tags, like `Name`, or `Labels`? or even pod name, where it is attached at first time?  

/triage support

**Comment by leakingtapan** [comment]
To be compatible with in-tree EBS plugin behavior, there is list of dynamic values I'm looking for adding. See [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/351#issue-483658726) for a complete list. 



> but, is it possible to put tags from enviroment variables?

Why do you need to set the tag through environment? Is there anything that is not enough with the cli flag from #333? 

From the examples you gave, it seem fitting into the [Add the ability to provide arbitrary EBS volume tags](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180) use case.

**Comment by mrPsycho** [comment]
to be honest, we are trying to add more functionality to new "jenkins core". and it is installed on Amazon AWS, what is obvious. 
After several adjustments we found, that cool PR, that allows us to add custom tag, like BackupStrateg, and now we are able to use AWS Backup solution. 

but there is a problem - how to find correct backup for needed "managed master"... so, we need a way how to put this tags.

as for now we have 2 options:
* before creating new master we have to edit configuration, and use `kubectl apply -f new.master.yaml` where we will add all necessary tags.
* after master is created - run something like that  
`kubectl get pv $(kubectl get pvc -l tenant=$mastername --no-headers -o custom-columns=":spec.volumeName") --no-headers -o custom-columns=":spec.awsElasticBlockStore.volumeID" ` and use aws cli to tag volume after. 

first way looks a bit better... but, maybe there are other options, and that's what i'm asking

**Comment by mrPsycho** [comment]
i have a progress: 
after reading https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ i noticed example:
```
- name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
```

and this almost that what is needed. 
I've tried this: 
```
- --extra-volume-tags=BackupStrategy=Hourly,Name=$(NAME)
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels.tenant
``` 
but it returns `ebs-csi-controller-0`
which is wrong.... 

How to find correct variable?
