### ISSUE TITLE
Not able to use EBS volume with Dynamic provisioning

### ISSUE THREAD

**Issue by vishnuravi3186** [kubernetes-sigs/aws-ebs-csi-driver#502]
I am trying to use EBS CSI Driver in my existing Kubernetes cluster , I am using latest version of CSI driver , I have 1 master and 3 worker nodes installed using kubeadm on aws, My Kubernetes version is "v1.18.1" ,  When I create PVC its in pending state and following is the error message i can see in the pvc log

 Normal   WaitForFirstConsumer  4m52s (x3 over 5m21s)  persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Normal   Provisioning          23s (x9 over 4m48s)    ebs.csi.aws.com_ebs-csi-controller-8466bbd8f9-ng9b7_886133b3-6d3a-4a0e-93df-4761c3c5fbc1  External provisioner is provisioning volume for claim "default/ebs-claim"
  Warning  ProvisioningFailed    22s (x9 over 4m44s)    ebs.csi.aws.com_ebs-csi-controller-8466bbd8f9-ng9b7_886133b3-6d3a-4a0e-93df-4761c3c5fbc1  failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = RequestError: send request failed
caused by: Post "https://ec2.us-east-1.amazonaws.com/": x509: certificate is valid for *.wpengine.com, wpengine.com, not ec2.us-east-1.amazonaws.com
  Normal  ExternalProvisioning  7s (x21 over 4m48s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator

Its not creating the pv

**Comment by jgallucci32** [comment]
@vishnuravi3186 I received the exact same error message when using a custom EC2 endpoint which has a company-signed SSL certificate. The problem would also present the same error is accessing the Amazon EC2 endpoints from behind an SSL proxy.

The following error message implies you are behind an SSL proxy presenting a different certificate
```
x509: certificate is valid for *.wpengine.com, wpengine.com, not ec2.us-east-1.amazonaws.com
```
There are a few ways to fix this, however, it is worth a discussion with the primary developers on how they want to handle this. One method would be to write the custom CA bundle into the csi-controller container as a secret or configMap and update the environment variable CA_BUNDLE (as documented in the aws-sdk-go). Another method would be to overwite the `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` file of the container. A third method would be to use a sidecar-injector which would benefit other pods and not just this CSI driver.

**Comment by jgallucci32** [comment]
@vishnuravi3186 If you want a quick fix try doing this.

Create **ConfigMap** for custom CA certificates
```
cat /path/to/custom/ca-bundle.crt > ca-certificates.crt
kubectl create configmap -n kube-system --from-file=ca-certificates.crt aws-config
```
Modify `ebs-csi-controller.yaml` to mount the new CA bundle to the CSI controller
```
# Add this to the ebs-plugin volumeMounts: section of the first container
#       volumeMounts:
        - name: config-volume
          mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          subPath: ca-certificates.crt
# Add this to the volumes: section toward the bottom
#     volumes:
      - name: config-volume
        configMap:
          name: aws-config
```
Redeploy the csi-controller pod and it will overwrite the existing CA bundle with the one supplied in the ConfigMap. It should allow you to hit an endpoint with a custom SSL certificate.
