### ISSUE TITLE
Support io2 EBS volumes

### ISSUE THREAD

**Issue by rawipfel** [kubernetes-sigs/aws-ebs-csi-driver#556]
/kind bug

**What happened?**

Pod with io2 PVC was pending

**What you expected to happen?**

Expected the latest CSI to support EBS io2 volumes

**How to reproduce it (as minimally and precisely as possible)?**

Create a StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io2
  iopsPerGB: "500"
```

Create a PVC with that class:
```
  volumeClaimTemplates:
    - metadata:
        name: mydata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: io2
        resources:
          requests:
            storage: 200Gi
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Default EKS
- Driver version:
"github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
