### ISSUE TITLE
CSIDriver should not be namespaced

### ISSUE THREAD

**Issue by groodt** [kubernetes-sigs/aws-ebs-csi-driver#590]
/kind bug

**What happened?**
Rendering the manifests like this:
`kubectl kustomize "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v0.7.0"`

Results in this resource:
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
  name: ebs.csi.aws.com
  namespace: kube-system
spec:
  attachRequired: true
  podInfoOnMount: false
```

This resource should not be namespaced according to:
`kubectl api-resources --namespaced=false`

**What you expected to happen?**
This resource should not have a namespace specified.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:
