### ISSUE TITLE
GRPC error: rpc error: code = NotFound desc = Instance "xxxxxxx" not found

### ISSUE THREAD

**Issue by pabrahamusa** [kubernetes-sigs/aws-ebs-csi-driver#611]
I want to attach a static "io2" to one of the nodes via pvc. I followed the document to set up the CSI https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html . I was able to create PV and PVC . And PV status is Bound and pvc status also Bound. However the container is not up and  getting following error . 

  **Warning  FailedAttachVolume  116s (x24 over 34m)  attachdetach-controller  AttachVolume.Attach failed for volume "my-pvc" : rpc error: code = NotFound desc = Instance "xxxxxxxxxxx" not found**

Following is from csi-controller pod

 csi_handler.go:534] Found NodeID i-0dc55388ab6f97184 in CSINode ip-100-72-xx-xx.ec2.internal
I1115 04:29:08.072825       1 csi_handler.go:168] VA finalizer is already set on "csi-93de06775916e37a0ed460b779482f7cf769f2b50dxxxxxxxxxxx"
I1115 04:29:08.072840       1 csi_handler.go:182] NodeID annotation is already set on "csi-93de06775916e37a0ed460b779482f7cf769f2b50dxxxxxxxxxxx"
I1115 04:29:08.072874       1 connection.go:180] GRPC call: /csi.v1.Controller/ControllerPublishVolume
I1115 04:29:08.072885       1 connection.go:181] GRPC request: {"node_id":"xxxxxxx","volume_capability":{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}},"volume_id":"vol-xxxxxxx"}
I1115 04:29:08.100600       1 connection.go:183] GRPC response: {}
**I1115 04:29:08.101048       1 connection.go:184] GRPC error: rpc error: code = NotFound desc = Instance "xxxxxx" not found**

StorageClass.yaml
----------------------
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: io2
```

pv.yaml
-------------
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pvc
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: io2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-xxxxxxxxx
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - us-east-1a
```

pv-claim.yaml
----------------------
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: io2
  resources:
    requests:
      storage: 100Gi
```

Test Pod
------------
```
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: my-pvc
  nodeSelector:
       "topology.ebs.csi.aws.com/zone": us-east-1a
```
