### ISSUE TITLE
ARM64 aws-ebs-csi-driver images have x86_64 binaries

### ISSUE THREAD

**Issue by sipsma** [kubernetes-sigs/aws-ebs-csi-driver#656]
/kind bug

**What happened?**
The arm64 aws-ebs-csi-driver images worked a few days ago but now all fail to run on arm64 machines. When I pull the images down and inspect them, they appear to all actually by x86 images even though they are labeled arm64. For example:
```
root@ip-10-0-0-243:~# ctr image pull --platform linux/arm64/v8 k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0
k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0:                                resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:a8ed0a90b49c16301f3ca934b75db63b8d5c8d68c377a865bce15c9af4a12ff5: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:a5e67acf34d2f09cafca63fd41b6f9898f216ee98dde8ddf235d8edef660baf5:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:4ba180b702c8b29f4d24cb24eeb91a26a5924e797a806bbca1b73d26b5fe8b1e:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:5c3bea1f2f52c6b3cc8be0463f49ba95a2490377d0f848670d1af2ed2d4c6882:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:592701b57e30c44d07074686878f910b68eaa2d4afc75d3c6d53bb58c8807cbc:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 0.3 s                                                                    total:   0.0 B (0.0 B/s)                                         
unpacking linux/arm64/v8 sha256:a8ed0a90b49c16301f3ca934b75db63b8d5c8d68c377a865bce15c9af4a12ff5...
done
root@ip-10-0-0-243:~# mkdir tmp
root@ip-10-0-0-243:~# ctr image mount --platform linux/arm64/v8 k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0 tmp
sha256:5bd728051e5a37f591e0acd0c50a51c6871e6953267f5be1c9021f892aca14a0
tmp
root@ip-10-0-0-243:~# file tmp/bin/aws-ebs-csi-driver 
tmp/bin/aws-ebs-csi-driver: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=vkjo8nBXgvNN8K9RGjgz/qEsEhwoBGlBqbFS0hG3t/REDBNNkQ3nfX4Tmp1I6c/P8UIQWGuL
gHzj00Ilr00, stripped
```

**What you expected to happen?**
For the arm64 images to have arm64 binaries

**How to reproduce it (as minimally and precisely as possible)?**
See commands above using `ctr` or just try to run the image on an arm64 machine.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by wongma7** [comment]
Trying to verify if it's fixed: how do I use `ctr images mount`?

$ ctr --version
ctr github.com/containerd/containerd v1.3.9
$ ctr image mount --platform linux/arm64/v8 gcr.io/k8s-staging-provider-aws/aws-ebs-csi-driver:latest
No help topic for 'mount'

**Comment by wongma7** [comment]
NVM, it's on 1.4 branch.

**Comment by wongma7** [comment]
@sipsma does `docker.io/amazon/aws-ebs-csi-driver:release-0.8-amazonlinux` work for you? I am still testing the fix, trying to ensure that the gcr build process (prow) and docker hub build process (github actions) stay identical

**Comment by sipsma** [comment]
@wongma7 No the issue still exists. Another way to test it with just docker instead of ctr is to try to run the image on an arm64 machine, i.e.:
```
root@ip-10-0-111-134:~# uname -a
Linux ip-10-0-111-134 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:08:09 UTC 2020 aarch64 aarch64 aarch64 GNU/L
root@ip-10-0-111-134:~# docker run --rm -it k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0
Unable to find image 'k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0' locally
v0.8.0: Pulling from provider-aws/aws-ebs-csi-driver
4ba180b702c8: Pull complete 
5c3bea1f2f52: Pull complete 
a5e67acf34d2: Pull complete 
Digest: sha256:a8ed0a90b49c16301f3ca934b75db63b8d5c8d68c377a865bce15c9af4a12ff5
Status: Downloaded newer image for k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by sipsma** [comment]
@wongma7 yes `docker.io/amazon/aws-ebs-csi-driver:release-0.8-amazonlinux` works for me now on an arm64 instance (the gcr one still fails like before)

**Comment by shrivastavshubham34** [comment]
@sipsma 
Are you deploying them using kustomization overlay? 
Because the below doesn't work for me
 ```
 kubectl apply -k aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/arm64/
 ```
 ```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base
images:
  - name: docker.io/amazon/aws-ebs-csi-driver
    newTag: "release-0.8-amazonlinux"
  - name: quay.io/k8scsi/csi-provisioner
    newName: raspbernetes/csi-external-provisioner
    newTag: "1.6.0"
  - name: quay.io/k8scsi/csi-attacher
    newName: raspbernetes/csi-external-attacher
    newTag: "2.2.0"
  - name: quay.io/k8scsi/livenessprobe
    newName: k8s.gcr.io/sig-storage/livenessprobe
    newTag: "v2.1.0"
  - name: quay.io/k8scsi/csi-node-driver-registrar
    newName: raspbernetes/csi-node-driver-registrar
    newTag: "1.3.0"


 ```
 Neither does this
 ```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: docker.io/amazon/aws-ebs-csi-driver
    newTag: release-0.8-amazonlinux
  - name: quay.io/k8scsi/csi-provisioner
    newTag: v1.5.0
  - name: quay.io/k8scsi/csi-attacher
    newTag: v2.2.0
  - name: quay.io/k8scsi/livenessprobe
    newTag: v2.1.0
  - name: quay.io/k8scsi/csi-node-driver-registrar
    newTag: v1.3.0

```
