### ISSUE TITLE
Look like "throughput" parameter just ignored when using type: gp3 in kind: StorageClass

### ISSUE THREAD

**Issue by Slach** [kubernetes-sigs/aws-ebs-csi-driver#709]
/kind bug

**What happened?**
after successful installation EBS CSI driver 0,8.0 to my AWS EKS 
I define the following custom storage class

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
parameters:
  fsType: ext4
  type: gp3
  iops: "4000"
  throughput: "1000"
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

I found in sources following comments which not present in official documentation 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html
```
Maximum throughput for gp3 is 1000. However, maximum throughput/iops for gp3 is 0.25
Since the default iops is 3000, set to 750.
```
so I applied 4000 iops and expect 1000 Mb/sec

after that, I apply following manifest
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbench-pv-claim-gp3
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-gp3
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: clickhousepro/dbench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          - name: FIO_SIZE
            value: "10G"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pv-claim-gp3
  backoffLimit: 4
```
which run following fio command
```
echo Testing Read Sequential Speed...
fio --randrepeat=0 --verify=0 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=read_seq --filename=/data/fiotest --bs=1M --iodepth=16 --size=10G --readwrite=read --time_based --ramp_time=2s --runtime=15s --thread --numjobs=8 --offset_increment=500M

echo Testing Write Sequential Speed...
fio --randrepeat=0 --verify=0 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=write_seq --filename=/data/fiotest --bs=1M --iodepth=16 --size=10G --readwrite=write --time_based --ramp_time=2s --runtime=15s --thread --numjobs=8 --offset_increment=500M
```
and got only 332-350MiB/s

**What you expected to happen?**
I expected 1000MiB/s throughput
 
**How to reproduce it (as minimally and precisely as possible)?**
just clone
https://github.com/Altinity/dbench
and run 
`apply-dbench-all-storage-classes.sh`

**Environment**
- Kubernetes version (use `kubectl version`): 1.17-EKS
- Driver version: 0.8.0
