### ISSUE TITLE
Helm chart: can't annotate storage classes

### ISSUE THREAD

**Issue by nicholasmhughes** [kubernetes-sigs/aws-ebs-csi-driver#733]
/kind bug

**What happened?**
The new ability to create storage classes within the chart is great. However, there isn't a mechanism to annotate the storage classes. This becomes important is you want to tag one as default.

**What you expected to happen?**
Annotations should be handled separately from the rest of the storage class YAML and inserted under metadata.

**How to reproduce it (as minimally and precisely as possible)?**
```
storageClasses:
  - name: ebs-sc
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
```

**Anything else we need to know?**:
I have the code for this. PR inbound.

**Environment**
- Kubernetes version (use `kubectl version`): v1.18.12
- Driver version: 0.9.0
