### ISSUE TITLE
Silent failure of gp3 provisioning on EKS

### ISSUE THREAD

**Issue by PhilThurston** [kubernetes-sigs/aws-ebs-csi-driver#737]
/kind bug

**What happened?**

Explicitly stating gp3 fails with an error saying that gp3 is not a valid volumeType

**What you expected to happen?**

Explicitly declaring any of the supported types should work

**How to reproduce it (as minimally and precisely as possible)?**
Using some of the basic examples
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

This fails with an error similar to this: 
```
failed to provision volume with StorageClass "gp3": rpc error: code = Internal desc = Could not create volume "pvc-c1508ab3-43dc-461a-b294-f4038ce93572": invalid AWS VolumeType "gp3"
```
**Anything else we need to know?**:

You can resolve this by simply not declaring `type: gp3` in the above storageClass

**Environment**
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Driver version: 0.8

**Comment by AndyXiangLi** [comment]
@PhilThurston I notice that you are using EKS cluster, ebs driver is not enabled on EKS cluster by default, do you enable the CSIMigration and CSIMigrationAWS feature-gate on your cluster?
You can check the actual provisioner involved by using command: kubectl describe pvc ebs-claim

**Comment by PhilThurston** [comment]
if it wasn't clear from my description I am able to provision gp3 drives without issue when I just remove the "type" field from the sc. that being said here is the full output from the pvc

```
Name:          ebs-claim
Namespace:     default
StorageClass:  gp3bad
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-10-10-1-249.us-west-2.compute.internal
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       app
Events:
  Type     Reason                Age                From                                                                                      Message
  ----     ------                ----               ----                                                                                      -------
  Normal   WaitForFirstConsumer  37s                persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Normal   ExternalProvisioning  12s (x3 over 37s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
  Normal   Provisioning          5s (x6 over 37s)   ebs.csi.aws.com_ebs-csi-controller-5f5d776cc9-cvffs_cc4a7179-f6bd-4964-bf27-4ae4a2aa6ce6  External provisioner is provisioning volume for claim "default/ebs-claim"
  Warning  ProvisioningFailed    5s (x6 over 37s)   ebs.csi.aws.com_ebs-csi-controller-5f5d776cc9-cvffs_cc4a7179-f6bd-4964-bf27-4ae4a2aa6ce6  failed to provision volume with StorageClass "gp3bad": rpc error: code = Internal desc = Could not create volume "pvc-5ec45f55-8429-4b9e-9606-c9cf8e461733": invalid AWS VolumeType "gp3"
```

**Comment by ayberk** [comment]
@PhilThurston there's no way to enable the CSI migration on a Kubernetes cluster. In-tree driver doesn't support gp3, so the error message makes sense. Are you sure the volumes created are not gp2 when you don't specify the type?

**Comment by PhilThurston** [comment]
You're right. While kubectl says that the pvc is bound and the pv shows up and is even povisioned by eks the ebs that is made is gp2 without stating as such. I would still consider this a bug as it does provision the EBS drive but can't attach. So it's silently failing without a verbose reason.

Below are the steps to reproduce:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3good
provisioner: ebs.csi.aws.com
parameters:
  # type: gp3
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3good
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
  - name: app2
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim2
```
output of `kubectl describe pvc ebs-claim2`
```
Name:          ebs-claim2
Namespace:     default
StorageClass:  gp3good
Status:        Bound
Volume:        pvc-3712f1bb-f12f-4f69-b1e7-08c4784b0920
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-10-10-1-246.us-west-2.compute.internal
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      4Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    app2
Events:
  Type    Reason                 Age                    From                                                                                      Message
  ----    ------                 ----                   ----                                                                                      -------
  Normal  WaitForFirstConsumer   9m25s                  persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Normal  Provisioning           9m25s                  ebs.csi.aws.com_ebs-csi-controller-5f5d776cc9-59b4f_4a22d7d8-5a58-4210-8d17-691d5ed55cfb  External provisioner is provisioning volume for claim "default/ebs-claim2"
  Normal  ExternalProvisioning   9m22s (x3 over 9m25s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
  Normal  ProvisioningSucceeded  9m21s                  ebs.csi.aws.com_ebs-csi-controller-5f5d776cc9-59b4f_4a22d7d8-5a58-4210-8d17-691d5ed55cfb  Successfully provisioned volume pvc-3712f1bb-f12f-4f69-b1e7-08c4784b0920
```
Output of `kubectl describe pod app2`
```
Name:         app2
Namespace:    default
Priority:     0
Node:         ip-10-10-1-246.us-west-2.compute.internal/10.10.1.246
Start Time:   Thu, 11 Feb 2021 15:48:16 -0700
Labels:       <none>
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           
IPs:          <none>
Containers:
  app2:
    Container ID:  
    Image:         centos
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do echo $(date -u) >> /data/out.txt; sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-znz2z (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ebs-claim2
    ReadOnly:   false
  default-token-znz2z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-znz2z
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Normal   Scheduled           10m                    default-scheduler        Successfully assigned default/app2 to ip-10-10-1-246.us-west-2.compute.internal
  Warning  FailedAttachVolume  2m17s (x4 over 8m21s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-3712f1bb-f12f-4f69-b1e7-08c4784b0920" : attachdetachment timeout for volume vol-0bcace804616191cc
  Warning  FailedMount         85s (x4 over 8m18s)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage default-token-znz2z]: timed out waiting for the condition
```

![image](https://user-images.githubusercontent.com/26198483/107709343-47bc4080-6c82-11eb-865b-0179471324ba.png)
