### ISSUE TITLE
[chart] 0.9.6 StorageClass Missing YAML Document Separator 

### ISSUE THREAD

**Issue by aballman** [kubernetes-sigs/aws-ebs-csi-driver#750]
/kind bug

**What happened?**
When using the `storageClasses` field in the helm chart and providing multiple entries, the generated yaml does not include the document separator `---`

```
# Source: aws-ebs-csi-driver/templates/storageclass.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc1
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
```

**What you expected to happen?**
The same yaml is generated with the document separator, so that N resources are created instead of 1.
```
# Source: aws-ebs-csi-driver/templates/storageclass.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc1
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
```

**How to reproduce it (as minimally and precisely as possible)?**
Using the following for your values
```
storageClasses:
- name: "sc1"
- name: "sc2"
```

**Anything else we need to know?**:
Nope

**Environment**
- Kubernetes version (use `kubectl version`): 1.18.9 EKS
- Driver version: 3.0.3
- Chart version: 0.9.6
