### ISSUE TITLE
Volume partitions are not supported

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#812]
/kind bug

**What happened?**
For CSI migration we need all in-tree features supported in the CSI driver. In-tree volumes support mounting volume partitions in  `pv.spec.awsElasticBlockStore.partition` flag. Such capability should be present in the CSI driver too.

**How to reproduce it (as minimally and precisely as possible)?**
Enable CSI migration and use following Pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: inline
spec:
  containers:
  - name: inline
    image: centos:7
    args:
    - sleep
    - '99999'
    volumeMounts:
    - mountPath: "/mnt/storage"
      name: inline
  volumes:
  - name: inline
    awsElasticBlockStore:
      fsType: xfs
      volumeID: vol-072b2b73e088c43b5
      partition: 1
```

**Anything else we need to know?**:
The CSI translation library makes the partition number available in `volume_attribute: partition`: https://github.com/kubernetes/kubernetes/blob/bbb58fa085ccfc4635aa8544686d960115449d95/staging/src/k8s.io/csi-translation-lib/plugins/aws_ebs.go#L112
