### ISSUE TITLE
Upgrade from 1.0.0 to 1.0.1 fails

### ISSUE THREAD

**Issue by languitar** [kubernetes-sigs/aws-ebs-csi-driver#883]
/kind bug

**What happened?**

Our cluster tried to auto-upgrade the Chart version from 1.0.0 to 1.0.1. This fails with the following error message:

> Helm upgrade failed: cannot patch "ebs-csi-node-binding" with kind ClusterRoleBinding: ClusterRoleBinding.rbac.authorization.k8s.io "ebs-csi-node-binding" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"ebs-csi-node-role"}: cannot change roleRef

**What you expected to happen?**

Upgrade for a patch version simply works

**How to reproduce it (as minimally and precisely as possible)?**

This is the helm release we use:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver-helm-charts
        namespace: flux-system
  interval: 1m0s
  values:
    # already the default, just be sure and document this
    priorityClassName: "system-cluster-critical"
    enableVolumeScheduling: true
    enableVolumeResizing: true
    enableVolumeSnapshot: true
    extraVolumeTags:
      "xxx:cost-center": xxx
      "xxx:contact-email": xxx
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
- Driver version: aws-ebs-csi-driver:v1.0.0 is running, helm tried to auto-upgrade to 1.0.1
